/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused",
)

package vote.fetcher.polishsejm.client.models

import com.squareup.moshi.Json
import vote.fetcher.polishsejm.client.models.SejmCommitteeSittingNumDto
import vote.fetcher.polishsejm.client.models.SejmSittingStatusDto
import vote.fetcher.polishsejm.client.models.SejmVideoDto

/**
 * A committee sitting.
 *
 * @param code A committee code
 * @param num A sitting number
 * @param date A sitting date
 * @param startDateTime A sitting start date
 * @param endDateTime A sitting end date
 * @param closed A flag indicating that a meeting is closed
 * @param remote A flag indicating that a meeting is a remote meeting
 * @param video A list of video transmissions
 * @param audio A link to an audio file
 * @param city A city where meeting took place
 * @param room A room where the sitting takes place
 * @param notes Additional notes
 * @param comments Additional comments
 * @param jointWith A list of committees at joint meeting
 * @param agenda An agenda of a meeting
 * @param status Status of the meeting
 */

data class SejmCommitteeSittingDto(
    // A committee code
    @Json(name = "code")
    val code: kotlin.String? = null,
    // A sitting number
    @Json(name = "num")
    val num: kotlin.Int? = null,
    // A sitting date
    @Json(name = "date")
    val date: java.time.LocalDate? = null,
    // A sitting start date
    @Json(name = "startDateTime")
    val startDateTime: java.time.LocalDateTime? = null,
    // A sitting end date
    @Json(name = "endDateTime")
    val endDateTime: java.time.LocalDateTime? = null,
    // A flag indicating that a meeting is closed
    @Json(name = "closed")
    val closed: kotlin.Boolean? = null,
    // A flag indicating that a meeting is a remote meeting
    @Json(name = "remote")
    val remote: kotlin.Boolean? = null,
    // A list of video transmissions
    @Json(name = "video")
    val video: kotlin.collections.List<SejmVideoDto>? = null,
    // A link to an audio file
    @Json(name = "audio")
    val audio: kotlin.String? = null,
    // A city where meeting took place
    @Json(name = "city")
    val city: kotlin.String? = null,
    // A room where the sitting takes place
    @Json(name = "room")
    val room: kotlin.String? = null,
    // Additional notes
    @Json(name = "notes")
    val notes: kotlin.String? = null,
    // Additional comments
    @Json(name = "comments")
    val comments: kotlin.String? = null,
    // A list of committees at joint meeting
    @Json(name = "jointWith")
    val jointWith: kotlin.collections.List<SejmCommitteeSittingNumDto>? = null,
    // An agenda of a meeting
    @Json(name = "agenda")
    val agenda: kotlin.String? = null,
    // Status of the meeting
    @Json(name = "status")
    val status: SejmSittingStatusDto? = null,
)
