/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused",
)

package vote.fetcher.polishsejm.client.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Procedural status of a legislative document in the Sejm
 *
 * Values: ACTIVE,WITHDRAWN,NOT_PROCEEDED,OBSOLETE,ADOPTED
 */

@JsonClass(generateAdapter = false)
enum class SejmBillStatusDto(val value: kotlin.String) {
    @Json(name = "ACTIVE")
    ACTIVE("ACTIVE"),

    @Json(name = "WITHDRAWN")
    WITHDRAWN("WITHDRAWN"),

    @Json(name = "NOT_PROCEEDED")
    NOT_PROCEEDED("NOT_PROCEEDED"),

    @Json(name = "OBSOLETE")
    OBSOLETE("OBSOLETE"),

    @Json(name = "ADOPTED")
    ADOPTED("ADOPTED"),
    ;

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is SejmBillStatusDto) "$data" else null

        /**
         * Returns a valid [SejmBillStatusDto] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): SejmBillStatusDto? =
            data?.let {
                val normalizedData = "$it".lowercase()
                entries.firstOrNull { value ->
                    it == value || normalizedData == "$value".lowercase()
                }
            }
    }
}
