/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused",
)

package vote.fetcher.polishsejm.client.models

import com.squareup.moshi.Json

/**
 * MP voting statistics
 *
 * @param sitting sitting number
 * @param date sitting date
 * @param numVotings number of votings on this day
 * @param numVoted number of MP votings on this day
 * @param numMissed number of votings missed on this day
 * @param absenceExcuse is there a excuse for absence
 */

data class SejmVotingStatDto(
    // sitting number
    @Json(name = "sitting")
    val sitting: kotlin.Int? = null,
    // sitting date
    @Json(name = "date")
    val date: java.time.LocalDate? = null,
    // number of votings on this day
    @Json(name = "numVotings")
    val numVotings: kotlin.Int? = null,
    // number of MP votings on this day
    @Json(name = "numVoted")
    val numVoted: kotlin.Int? = null,
    // number of votings missed on this day
    @Json(name = "numMissed")
    val numMissed: kotlin.Int? = null,
    // is there a excuse for absence
    @Json(name = "absenceExcuse")
    val absenceExcuse: kotlin.Boolean? = null,
)
