/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused",
)

package vote.fetcher.polishsejm.client.models

import com.squareup.moshi.Json

/**
 * A document in the legislative process.
 *
 * @param number a print number
 * @param registeredDate a date when a document was registered
 * @param documentDate a date of a document
 * @param title a title of a print
 */

data class SejmProcessDocumentDto(
    // a print number
    @Json(name = "number")
    val number: kotlin.String? = null,
    // a date when a document was registered
    @Json(name = "registeredDate")
    val registeredDate: java.time.LocalDate? = null,
    // a date of a document
    @Json(name = "documentDate")
    val documentDate: java.time.LocalDate? = null,
    // a title of a print
    @Json(name = "title")
    val title: kotlin.String? = null,
)
