/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused",
)

package vote.fetcher.polishsejm.client.models

import com.squareup.moshi.Json
import vote.fetcher.polishsejm.client.models.SejmProcessStageDto

/**
 * reading on Sejm sitting
 *
 * @param stageName a name of a stage
 * @param date a stage date
 * @param children child stages
 * @param sittingNum Sejm sitting number
 * @param comment comment
 * @param decision decision
 * @param textAfter3 a link to a text after third reading (in a PDF format)
 * @param stageType
 */

data class SejmProcessStageSejmReadingDto(
    // a name of a stage
    @Json(name = "stageName")
    val stageName: kotlin.String? = null,
    // a stage date
    @Json(name = "date")
    val date: java.time.LocalDate? = null,
    // child stages
    @Json(name = "children")
    val children: kotlin.collections.List<SejmProcessStageDto>? = null,
    // Sejm sitting number
    @Json(name = "sittingNum")
    val sittingNum: kotlin.Int? = null,
    // comment
    @Json(name = "comment")
    val comment: kotlin.String? = null,
    // decision
    @Json(name = "decision")
    val decision: kotlin.String? = null,
    // a link to a text after third reading (in a PDF format)
    @Json(name = "textAfter3")
    val textAfter3: kotlin.String? = null,
    @Json(name = "stageType")
    val stageType: kotlin.String? = null,
)
