/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused",
)

package vote.fetcher.polishsejm.client.models

import com.squareup.moshi.Json
import vote.fetcher.polishsejm.client.models.SejmAttachmentDto

/**
 * reply to an interpellation or question
 *
 * @param key a reply identifier
 * @param receiptDate A date when the reply was received
 * @param lastModified A date of last modification of a document
 * @param from A name of an author
 * @param links Links to HTML page with a description or a content (body)
 * @param onlyAttachment Flag indicating that this reply contains only an attachment (without HTML body)
 * @param attachments Attachments
 * @param prolongation Is this reply a prolongation. Text of prolongation is not published.
 */

data class SejmReplyDto(
    // a reply identifier
    @Json(name = "key")
    val key: kotlin.String? = null,
    // A date when the reply was received
    @Json(name = "receiptDate")
    val receiptDate: java.time.LocalDate? = null,
    // A date of last modification of a document
    @Json(name = "lastModified")
    val lastModified: java.time.LocalDateTime? = null,
    // A name of an author
    @Json(name = "from")
    val from: kotlin.String? = null,
    // Links to HTML page with a description or a content (body)
    @Json(name = "links")
    val links: kotlin.collections.List<kotlin.Any?>? = null,
    // Flag indicating that this reply contains only an attachment (without HTML body)
    @Json(name = "onlyAttachment")
    val onlyAttachment: kotlin.Boolean? = null,
    // Attachments
    @Json(name = "attachments")
    val attachments: kotlin.collections.List<SejmAttachmentDto>? = null,
    // Is this reply a prolongation. Text of prolongation is not published.
    @Json(name = "prolongation")
    val prolongation: kotlin.Boolean? = null,
)
