/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused",
)

package vote.fetcher.polishsejm.client.models

import com.squareup.moshi.Json
import vote.fetcher.polishsejm.client.models.SejmProcessStageDto
import vote.fetcher.polishsejm.client.models.SejmReferralTypeDto

/**
 * referral
 *
 * @param stageName a name of a stage
 * @param date a stage date
 * @param children child stages
 * @param type referral type
 * @param committeeCode a committee code or null for Sejm reading
 * @param reportDate recommended date of report
 * @param remarks remarks
 * @param stageType
 */

data class SejmProcessStageReferralDto(
    // a name of a stage
    @Json(name = "stageName")
    val stageName: kotlin.String? = null,
    // a stage date
    @Json(name = "date")
    val date: java.time.LocalDate? = null,
    // child stages
    @Json(name = "children")
    val children: kotlin.collections.List<SejmProcessStageDto>? = null,
    // referral type
    @Json(name = "type")
    val type: SejmReferralTypeDto? = null,
    // a committee code or null for Sejm reading
    @Json(name = "committeeCode")
    val committeeCode: kotlin.String? = null,
    // recommended date of report
    @Json(name = "reportDate")
    val reportDate: java.time.LocalDate? = null,
    // remarks
    @Json(name = "remarks")
    val remarks: kotlin.String? = null,
    @Json(name = "stageType")
    val stageType: kotlin.String? = null,
)
