/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused",
)

package vote.fetcher.polishsejm.client.models

import com.squareup.moshi.Json
import vote.fetcher.polishsejm.client.models.SejmVoteValueDto
import vote.fetcher.polishsejm.client.models.SejmVotingKindDto

/**
 * a vote used in MP votings
 *
 * @param votingNumber a voting number
 * @param date a voting date and time
 * @param kind a kind of voting
 * @param title a voting title
 * @param description description
 * @param topic a voting topic
 * @param vote a vote
 * @param listVotes 'yes' votes on a list
 */

data class SejmVoteMPDto(
    // a voting number
    @Json(name = "votingNumber")
    val votingNumber: kotlin.Int? = null,
    // a voting date and time
    @Json(name = "date")
    val date: java.time.LocalDateTime? = null,
    // a kind of voting
    @Json(name = "kind")
    val kind: SejmVotingKindDto? = null,
    // a voting title
    @Json(name = "title")
    val title: kotlin.String? = null,
    // description
    @Json(name = "description")
    val description: kotlin.String? = null,
    // a voting topic
    @Json(name = "topic")
    val topic: kotlin.String? = null,
    // a vote
    @Json(name = "vote")
    val vote: SejmVoteValueDto? = null,
    // 'yes' votes on a list
    @Json(name = "listVotes")
    val listVotes: kotlin.collections.Map<kotlin.String, kotlin.String>? = null,
)
