/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused",
)

package vote.fetcher.polishsejm.client.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 *
 *
 * Values: DRAFT_RESOLUTION,BILL,OTHER,CONSTITUTIONAL_TRIBUNAL_RULING
 */

@JsonClass(generateAdapter = false)
enum class SejmProcessTypeDto(val value: kotlin.String) {
    @Json(name = "DRAFT_RESOLUTION")
    DRAFT_RESOLUTION("DRAFT_RESOLUTION"),

    @Json(name = "BILL")
    BILL("BILL"),

    @Json(name = "OTHER")
    OTHER("OTHER"),

    @Json(name = "CONSTITUTIONAL_TRIBUNAL_RULING")
    CONSTITUTIONAL_TRIBUNAL_RULING("CONSTITUTIONAL_TRIBUNAL_RULING"),
    ;

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is SejmProcessTypeDto) "$data" else null

        /**
         * Returns a valid [SejmProcessTypeDto] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): SejmProcessTypeDto? =
            data?.let {
                val normalizedData = "$it".lowercase()
                entries.firstOrNull { value ->
                    it == value || normalizedData == "$value".lowercase()
                }
            }
    }
}
