/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused",
)

package vote.fetcher.polishsejm.client.models

import com.squareup.moshi.Json
import vote.fetcher.polishsejm.client.models.SejmMemberDto

/**
 * A parliamentary club.
 *
 * @param id Club identifier.
 * @param name Name of the club
 * @param phone Phone number to the club
 * @param fax Fax number to the club
 * @param email Email address to the club
 * @param membersCount Number of club members
 * @param members List of members
 */

data class SejmClubDto(
    // Club identifier.
    @Json(name = "id")
    val id: kotlin.String,
    // Name of the club
    @Json(name = "name")
    val name: kotlin.String? = null,
    // Phone number to the club
    @Json(name = "phone")
    val phone: kotlin.String? = null,
    // Fax number to the club
    @Json(name = "fax")
    val fax: kotlin.String? = null,
    // Email address to the club
    @Json(name = "email")
    val email: kotlin.String? = null,
    // Number of club members
    @Json(name = "membersCount")
    val membersCount: kotlin.Int? = null,
    // List of members
    @Json(name = "members")
    val members: kotlin.collections.List<SejmMemberDto>? = null,
)
