/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused",
)

package vote.fetcher.polishsejm.client.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 *
 *
 * Values: NORMAL,ADDITIONAL,OPINION,ADDITIONAL_OPINION,WITHDRAWAL
 */

@JsonClass(generateAdapter = false)
enum class SejmReferralTypeDto(val value: kotlin.String) {
    @Json(name = "NORMAL")
    NORMAL("NORMAL"),

    @Json(name = "ADDITIONAL")
    ADDITIONAL("ADDITIONAL"),

    @Json(name = "OPINION")
    OPINION("OPINION"),

    @Json(name = "ADDITIONAL_OPINION")
    ADDITIONAL_OPINION("ADDITIONAL_OPINION"),

    @Json(name = "WITHDRAWAL")
    WITHDRAWAL("WITHDRAWAL"),
    ;

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is SejmReferralTypeDto) "$data" else null

        /**
         * Returns a valid [SejmReferralTypeDto] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): SejmReferralTypeDto? =
            data?.let {
                val normalizedData = "$it".lowercase()
                entries.firstOrNull { value ->
                    it == value || normalizedData == "$value".lowercase()
                }
            }
    }
}
