/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused",
)

package vote.fetcher.polishsejm.client.models

import com.squareup.moshi.Json
import vote.fetcher.polishsejm.client.models.SejmStatementDto

/**
 *
 *
 * @param proceedingNum
 * @param date
 * @param statements
 */

data class SejmStatementListDto(
    @Json(name = "proceedingNum")
    val proceedingNum: kotlin.Int? = null,
    @Json(name = "date")
    val date: java.time.LocalDate? = null,
    @Json(name = "statements")
    val statements: kotlin.collections.List<SejmStatementDto>? = null,
)
