/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused",
)

package vote.fetcher.polishsejm.client.models

import com.squareup.moshi.Json
import vote.fetcher.polishsejm.client.models.SejmProcessStageDto

/**
 * opinion
 *
 * @param stageName a name of a stage
 * @param date a stage date
 * @param children child stages
 * @param organ organ
 * @param opinionReceived date when the opinion was received
 * @param toCommission date when the opinion was sent to commission
 * @param stageType
 */

data class SejmProcessStageOpinionDto(
    // a name of a stage
    @Json(name = "stageName")
    val stageName: kotlin.String? = null,
    // a stage date
    @Json(name = "date")
    val date: java.time.LocalDate? = null,
    // child stages
    @Json(name = "children")
    val children: kotlin.collections.List<SejmProcessStageDto>? = null,
    // organ
    @Json(name = "organ")
    val organ: kotlin.String? = null,
    // date when the opinion was received
    @Json(name = "opinionReceived")
    val opinionReceived: java.time.LocalDate? = null,
    // date when the opinion was sent to commission
    @Json(name = "toCommission")
    val toCommission: java.time.LocalDate? = null,
    @Json(name = "stageType")
    val stageType: kotlin.String? = null,
)
