/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused",
)

package vote.fetcher.polishsejm.client.models

import com.squareup.moshi.Json
import vote.fetcher.polishsejm.client.models.SejmProcessDocumentDto
import vote.fetcher.polishsejm.client.models.SejmProcessStageDto

/**
 * committee report
 *
 * @param stageName a name of a stage
 * @param date a stage date
 * @param children child stages
 * @param subCommittee is this subcommittee report
 * @param reportFile an URL to a report
 * @param printNumber a print number
 * @param rapporteurName a name of the MP
 * @param rapporteurID an ID of the MP
 * @param minorityMotions number of minority motions
 * @param proposal commission proposal
 * @param comment commission proposal comment
 * @param otherDocuments other documents, e.g. errata
 * @param stageType
 */

data class SejmProcessStageCommitteeReportDto(
    // a name of a stage
    @Json(name = "stageName")
    val stageName: kotlin.String? = null,
    // a stage date
    @Json(name = "date")
    val date: java.time.LocalDate? = null,
    // child stages
    @Json(name = "children")
    val children: kotlin.collections.List<SejmProcessStageDto>? = null,
    // is this subcommittee report
    @Json(name = "subCommittee")
    val subCommittee: kotlin.Boolean? = null,
    // an URL to a report
    @Json(name = "reportFile")
    val reportFile: kotlin.String? = null,
    // a print number
    @Json(name = "printNumber")
    val printNumber: kotlin.String? = null,
    // a name of the MP
    @Json(name = "rapporteurName")
    val rapporteurName: kotlin.String? = null,
    // an ID of the MP
    @Json(name = "rapporteurID")
    val rapporteurID: kotlin.String? = null,
    // number of minority motions
    @Json(name = "minorityMotions")
    val minorityMotions: kotlin.Int? = null,
    // commission proposal
    @Json(name = "proposal")
    val proposal: kotlin.String? = null,
    // commission proposal comment
    @Json(name = "comment")
    val comment: kotlin.String? = null,
    // other documents, e.g. errata
    @Json(name = "otherDocuments")
    val otherDocuments: kotlin.collections.List<SejmProcessDocumentDto>? = null,
    @Json(name = "stageType")
    val stageType: kotlin.String? = null,
)
