/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused",
)

package vote.fetcher.polishsejm.client.models

import com.squareup.moshi.Json
import vote.fetcher.polishsejm.client.models.SejmMemberTypeDto

/**
 *
 *
 * @param name A function name in the committee or in the club.
 * @param functionType A function name in English
 * @param appointmentDate A date of appointment
 * @param dismissalDate A date of dismissal
 */

data class SejmFunctionDto(
    // A function name in the committee or in the club.
    @Json(name = "name")
    val name: kotlin.String? = null,
    // A function name in English
    @Json(name = "functionType")
    val functionType: SejmMemberTypeDto? = null,
    // A date of appointment
    @Json(name = "appointmentDate")
    val appointmentDate: java.time.LocalDate? = null,
    // A date of dismissal
    @Json(name = "dismissalDate")
    val dismissalDate: java.time.LocalDate? = null,
)
