/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused",
)

package vote.fetcher.polishsejm.client.models

import com.squareup.moshi.Json
import vote.fetcher.polishsejm.client.models.SejmFunctionDto

/**
 * A member of a committee, parliamentary team or a club.
 *
 * @param id A number of the identity card of the MP.
 * @param lastFirstName The last and first name of the MP.
 * @param firstName The first name of the MP.
 * @param lastName The last name of the MP.
 * @param function A function in the committee or the club.
 * @param mandateExpired A date of expiry of the parliamentary mandate.
 * @param joinDate A date of joining a club or committee.
 * @param leaveDate A date of leaving a club or committee.
 * @param club A club to where MP is belonging
 * @param functions
 */

data class SejmMemberDto(
    // A number of the identity card of the MP.
    @Json(name = "id")
    val id: kotlin.Int? = null,
    // The last and first name of the MP.
    @Json(name = "lastFirstName")
    @Deprecated(message = "This property is deprecated.")
    val lastFirstName: kotlin.String? = null,
    // The first name of the MP.
    @Json(name = "firstName")
    val firstName: kotlin.String? = null,
    // The last name of the MP.
    @Json(name = "lastName")
    val lastName: kotlin.String? = null,
    // A function in the committee or the club.
    @Json(name = "function")
    val function: kotlin.String? = null,
    // A date of expiry of the parliamentary mandate.
    @Json(name = "mandateExpired")
    val mandateExpired: java.time.LocalDate? = null,
    // A date of joining a club or committee.
    @Json(name = "joinDate")
    val joinDate: java.time.LocalDate? = null,
    // A date of leaving a club or committee.
    @Json(name = "leaveDate")
    val leaveDate: java.time.LocalDate? = null,
    // A club to where MP is belonging
    @Json(name = "club")
    val club: kotlin.String? = null,
    @Json(name = "functions")
    val functions: kotlin.collections.List<SejmFunctionDto>? = null,
)
