/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused",
)

package vote.fetcher.polishsejm.client.models

import com.squareup.moshi.Json
import vote.fetcher.polishsejm.client.models.SejmGroupMemberDto

/**
 * A group details
 *
 * @param id ID used to get group details
 * @param name Name of the group
 * @param engName Name of the group in english
 * @param appointmentDate appointment date
 * @param remarks remarks
 * @param members members
 */

data class SejmGroupDetailsDto(
    // ID used to get group details
    @Json(name = "id")
    val id: kotlin.Int? = null,
    // Name of the group
    @Json(name = "name")
    val name: kotlin.String? = null,
    // Name of the group in english
    @Json(name = "engName")
    val engName: kotlin.String? = null,
    // appointment date
    @Json(name = "appointmentDate")
    val appointmentDate: java.time.LocalDate? = null,
    // remarks
    @Json(name = "remarks")
    val remarks: kotlin.String? = null,
    // members
    @Json(name = "members")
    val members: kotlin.collections.List<SejmGroupMemberDto>? = null,
)
