/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused",
)

package vote.fetcher.polishsejm.client.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 *
 *
 * Values: YES,NO,ABSTAIN,NO_VOTE,ABSENT,VOTE_VALID,VOTE_INVALID,PRESENT
 */

@JsonClass(generateAdapter = false)
enum class SejmVoteValueDto(val value: kotlin.String) {
    @Json(name = "YES")
    YES("YES"),

    @Json(name = "NO")
    NO("NO"),

    @Json(name = "ABSTAIN")
    ABSTAIN("ABSTAIN"),

    @Json(name = "NO_VOTE")
    NO_VOTE("NO_VOTE"),

    @Json(name = "ABSENT")
    ABSENT("ABSENT"),

    @Json(name = "VOTE_VALID")
    VOTE_VALID("VOTE_VALID"),

    @Json(name = "VOTE_INVALID")
    VOTE_INVALID("VOTE_INVALID"),

    @Json(name = "PRESENT")
    PRESENT("PRESENT"),
    ;

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is SejmVoteValueDto) "$data" else null

        /**
         * Returns a valid [SejmVoteValueDto] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): SejmVoteValueDto? =
            data?.let {
                val normalizedData = "$it".lowercase()
                entries.firstOrNull { value ->
                    it == value || normalizedData == "$value".lowercase()
                }
            }
    }
}
