/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused",
)

package vote.fetcher.polishsejm.client.models

import com.squareup.moshi.Json

/**
 * Details of a correspondence with a recipient
 *
 * @param name name of a recipient
 * @param sent date when a case was sent
 * @param answerDelayedDays number of days an answer is delayed for a given case. When an answer was given then the delay is set to 0.
 */

data class SejmCaseRecipientDetailsDto(
    // name of a recipient
    @Json(name = "name")
    val name: kotlin.String? = null,
    // date when a case was sent
    @Json(name = "sent")
    val sent: java.time.LocalDate? = null,
    // number of days an answer is delayed for a given case. When an answer was given then the delay is set to 0.
    @Json(name = "answerDelayedDays")
    val answerDelayedDays: kotlin.Int? = null,
)
