/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused",
)

package vote.fetcher.polishsejm.client.models

import com.squareup.moshi.Json
import vote.fetcher.polishsejm.client.models.SejmProcessStageDto

/**
 * an end stage in the legislative process
 *
 * @param stageName a name of a stage
 * @param date a stage date
 * @param children child stages
 * @param comment a comment
 * @param stageType
 */

data class SejmProcessStageEndDto(
    // a name of a stage
    @Json(name = "stageName")
    val stageName: kotlin.String? = null,
    // a stage date
    @Json(name = "date")
    val date: java.time.LocalDate? = null,
    // child stages
    @Json(name = "children")
    val children: kotlin.collections.List<SejmProcessStageDto>? = null,
    // a comment
    @Json(name = "comment")
    val comment: kotlin.String? = null,
    @Json(name = "stageType")
    val stageType: kotlin.String? = null,
)
