/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused",
)

package vote.fetcher.polishsejm.client.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 *
 *
 * Values: SIMPLE_MAJORITY,STATUTORY_MAJORITY,ABSOLUTE_MAJORITY,ABSOLUTE_STATUTORY_MAJORITY,MAJORITY_TWO_THIRDS,STATUTORY_MAJORITY_TWO_THIRDS,MAJORITY_THREE_FIFTHS,STATUTORY_MAJORITY_THREE_FIFTHS
 */

@JsonClass(generateAdapter = false)
enum class SejmVotingMajorityDto(val value: kotlin.String) {
    @Json(name = "SIMPLE_MAJORITY")
    SIMPLE_MAJORITY("SIMPLE_MAJORITY"),

    @Json(name = "STATUTORY_MAJORITY")
    STATUTORY_MAJORITY("STATUTORY_MAJORITY"),

    @Json(name = "ABSOLUTE_MAJORITY")
    ABSOLUTE_MAJORITY("ABSOLUTE_MAJORITY"),

    @Json(name = "ABSOLUTE_STATUTORY_MAJORITY")
    ABSOLUTE_STATUTORY_MAJORITY("ABSOLUTE_STATUTORY_MAJORITY"),

    @Json(name = "MAJORITY_TWO_THIRDS")
    MAJORITY_TWO_THIRDS("MAJORITY_TWO_THIRDS"),

    @Json(name = "STATUTORY_MAJORITY_TWO_THIRDS")
    STATUTORY_MAJORITY_TWO_THIRDS("STATUTORY_MAJORITY_TWO_THIRDS"),

    @Json(name = "MAJORITY_THREE_FIFTHS")
    MAJORITY_THREE_FIFTHS("MAJORITY_THREE_FIFTHS"),

    @Json(name = "STATUTORY_MAJORITY_THREE_FIFTHS")
    STATUTORY_MAJORITY_THREE_FIFTHS("STATUTORY_MAJORITY_THREE_FIFTHS"),
    ;

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is SejmVotingMajorityDto) "$data" else null

        /**
         * Returns a valid [SejmVotingMajorityDto] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): SejmVotingMajorityDto? =
            data?.let {
                val normalizedData = "$it".lowercase()
                entries.firstOrNull { value ->
                    it == value || normalizedData == "$value".lowercase()
                }
            }
    }
}
