/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused",
)

package vote.fetcher.polishsejm.client.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Type of applicant
 *
 * Values: DEPUTIES,COMMITTEE,GOVERNMENT,PRESIDIUM,PRESIDENT,SENATE,CITIZENS
 */

@JsonClass(generateAdapter = false)
enum class SejmApplicantTypeDto(val value: kotlin.String) {
    @Json(name = "DEPUTIES")
    DEPUTIES("DEPUTIES"),

    @Json(name = "COMMITTEE")
    COMMITTEE("COMMITTEE"),

    @Json(name = "GOVERNMENT")
    GOVERNMENT("GOVERNMENT"),

    @Json(name = "PRESIDIUM")
    PRESIDIUM("PRESIDIUM"),

    @Json(name = "PRESIDENT")
    PRESIDENT("PRESIDENT"),

    @Json(name = "SENATE")
    SENATE("SENATE"),

    @Json(name = "CITIZENS")
    CITIZENS("CITIZENS"),
    ;

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is SejmApplicantTypeDto) "$data" else null

        /**
         * Returns a valid [SejmApplicantTypeDto] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): SejmApplicantTypeDto? =
            data?.let {
                val normalizedData = "$it".lowercase()
                entries.firstOrNull { value ->
                    it == value || normalizedData == "$value".lowercase()
                }
            }
    }
}
