/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused",
)

package vote.fetcher.polishsejm.client.models

import com.squareup.moshi.Json

/**
 * statement on a sitting
 *
 * @param num statement number, 0 is always for course of the sitting
 * @param function function of the speaker
 * @param name name of the speaker
 * @param memberID MP id number, if speaker is an MP, 0 otherwise
 * @param rapporteur this statement was made by the rapporteur
 * @param secretary this statement was made by the secretary
 * @param startDateTime start time of the statement
 * @param endDateTime end time of the statement
 * @param unspoken is this is unspoken statement
 */

data class SejmStatementDto(
    // statement number, 0 is always for course of the sitting
    @Json(name = "num")
    val num: kotlin.Int? = null,
    // function of the speaker
    @Json(name = "function")
    val function: kotlin.String? = null,
    // name of the speaker
    @Json(name = "name")
    val name: kotlin.String? = null,
    // MP id number, if speaker is an MP, 0 otherwise
    @Json(name = "memberID")
    val memberID: kotlin.Int? = null,
    // this statement was made by the rapporteur
    @Json(name = "rapporteur")
    val rapporteur: kotlin.Boolean? = null,
    // this statement was made by the secretary
    @Json(name = "secretary")
    val secretary: kotlin.Boolean? = null,
    // start time of the statement
    @Json(name = "startDateTime")
    val startDateTime: java.time.LocalDateTime? = null,
    // end time of the statement
    @Json(name = "endDateTime")
    val endDateTime: java.time.LocalDateTime? = null,
    // is this is unspoken statement
    @Json(name = "unspoken")
    val unspoken: kotlin.Boolean? = null,
)
