/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused",
)

package vote.fetcher.polishsejm.client.models

import com.squareup.moshi.Json

/**
 * A proceeding.
 *
 * @param title a title of the proceeding
 * @param dates a dates of the proceeding
 * @param current is this a current proceeding
 * @param agenda agenda of a proceeding
 * @param schedule schedule of a proceeding (only for current proceeding)
 * @param votings schedule of votings for a proceeding (only for current proceeding)
 * @param currentAffairs current information and questions on current affairs (only for current proceeding)
 * @param number a proceeding number
 */

data class SejmProceedingDto(
    // a title of the proceeding
    @Json(name = "title")
    val title: kotlin.String? = null,
    // a dates of the proceeding
    @Json(name = "dates")
    val dates: kotlin.collections.List<java.time.LocalDate>? = null,
    // is this a current proceeding
    @Json(name = "current")
    val current: kotlin.Boolean? = null,
    // agenda of a proceeding
    @Json(name = "agenda")
    val agenda: kotlin.String? = null,
    // schedule of a proceeding (only for current proceeding)
    @Json(name = "schedule")
    val schedule: kotlin.String? = null,
    // schedule of votings for a proceeding (only for current proceeding)
    @Json(name = "votings")
    val votings: kotlin.String? = null,
    // current information and questions on current affairs (only for current proceeding)
    @Json(name = "currentAffairs")
    val currentAffairs: kotlin.String? = null,
    // a proceeding number
    @Json(name = "number")
    val number: kotlin.Int? = null,
)
