/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused",
)

package vote.fetcher.polishsejm.client.models

import com.squareup.moshi.Json
import vote.fetcher.polishsejm.client.models.SejmPrintInfoDto

/**
 * information about a term of the Sejm
 *
 * @param num Number of term of the Sejm
 * @param from Date start of term
 * @param to Date end of term
 * @param current Current of term
 * @param prints info about prints
 */

data class SejmTermDto(
    // Number of term of the Sejm
    @Json(name = "num")
    val num: kotlin.Int? = null,
    // Date start of term
    @Json(name = "from")
    val from: java.time.LocalDate? = null,
    // Date end of term
    @Json(name = "to")
    val to: java.time.LocalDate? = null,
    // Current of term
    @Json(name = "current")
    val current: kotlin.Boolean? = null,
    // info about prints
    @Json(name = "prints")
    val prints: SejmPrintInfoDto? = null,
)
