/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused",
)

package vote.fetcher.polishsejm.client.models

import com.squareup.moshi.Json

/**
 * info about a proceeding day
 *
 * @param proceeding proceeding number
 * @param date proceeding date
 * @param votingsNum number of votings on this day
 */

data class SejmProceedingDayDto(
    // proceeding number
    @Json(name = "proceeding")
    val proceeding: kotlin.Int? = null,
    // proceeding date
    @Json(name = "date")
    val date: java.time.LocalDate? = null,
    // number of votings on this day
    @Json(name = "votingsNum")
    val votingsNum: kotlin.Int? = null,
)
