/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused",
)

package vote.fetcher.polishsejm.client.models

import com.squareup.moshi.Json
import vote.fetcher.polishsejm.client.models.SejmProcessDocumentDto
import vote.fetcher.polishsejm.client.models.SejmProcessStageDto

/**
 * process start
 *
 * @param stageName a name of a stage
 * @param date a stage date
 * @param children child stages
 * @param printNumber print number
 * @param otherDocuments other prints, corrections
 * @param stageType
 */

data class SejmProcessStageStartDto(
    // a name of a stage
    @Json(name = "stageName")
    val stageName: kotlin.String? = null,
    // a stage date
    @Json(name = "date")
    val date: java.time.LocalDate? = null,
    // child stages
    @Json(name = "children")
    val children: kotlin.collections.List<SejmProcessStageDto>? = null,
    // print number
    @Json(name = "printNumber")
    val printNumber: kotlin.String? = null,
    // other prints, corrections
    @Json(name = "otherDocuments")
    val otherDocuments: kotlin.collections.List<SejmProcessDocumentDto>? = null,
    @Json(name = "stageType")
    val stageType: kotlin.String? = null,
)
