/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused",
)

package vote.fetcher.polishsejm.client.models

import com.squareup.moshi.Json
import vote.fetcher.polishsejm.client.models.SejmCaseRecipientDetailsDto
import vote.fetcher.polishsejm.client.models.SejmReplyDto

/**
 * An interpellation (pl: interpelacja).
 *
 * @param term A Sejm term when the document was submitted
 * @param num A document number
 * @param title A title of the case
 * @param receiptDate A date when the case was received
 * @param lastModified A date of last modification of a document
 * @param links Links to HTML pages with a description or a content (body)
 * @param from A list of IDs of MPs who submitted the question
 * @param to A list of ministries to whom the question was sent
 * @param recipientDetails A more detailed list of ministries to whom the question was sent
 * @param sentDate A date when the interpellation was sent to recipients
 * @param replies A list of replies
 * @param answerDelayedDays number of days an answer is delayed for a given case. When there are multiple recipients then a maximum value is taken.
 * @param repeatedInterpellation a list of interpellations that were submitted after reciving unsatisfactory answer (request for additional explanations)
 */

data class SejmInterpellationDto(
    // A Sejm term when the document was submitted
    @Json(name = "term")
    val term: kotlin.Int? = null,
    // A document number
    @Json(name = "num")
    val num: kotlin.Int? = null,
    // A title of the case
    @Json(name = "title")
    val title: kotlin.String? = null,
    // A date when the case was received
    @Json(name = "receiptDate")
    val receiptDate: java.time.LocalDate? = null,
    // A date of last modification of a document
    @Json(name = "lastModified")
    val lastModified: java.time.LocalDateTime? = null,
    // Links to HTML pages with a description or a content (body)
    @Json(name = "links")
    val links: kotlin.collections.List<kotlin.Any?>? = null,
    // A list of IDs of MPs who submitted the question
    @Json(name = "from")
    val from: kotlin.collections.List<kotlin.String>? = null,
    // A list of ministries to whom the question was sent
    @Json(name = "to")
    val to: kotlin.collections.List<kotlin.String>? = null,
    // A more detailed list of ministries to whom the question was sent
    @Json(name = "recipientDetails")
    val recipientDetails: kotlin.collections.List<SejmCaseRecipientDetailsDto>? = null,
    // A date when the interpellation was sent to recipients
    @Json(name = "sentDate")
    val sentDate: java.time.LocalDate? = null,
    // A list of replies
    @Json(name = "replies")
    val replies: kotlin.collections.List<SejmReplyDto>? = null,
    // number of days an answer is delayed for a given case. When there are multiple recipients then a maximum value is taken.
    @Json(name = "answerDelayedDays")
    val answerDelayedDays: kotlin.Int? = null,
    // a list of interpellations that were submitted after reciving unsatisfactory answer (request for additional explanations)
    @Json(name = "repeatedInterpellation")
    val repeatedInterpellation: kotlin.collections.List<SejmInterpellationDto>? = null,
)
