/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused",
)

package vote.fetcher.polishsejm.client.models

import com.squareup.moshi.Json

/**
 * An attachment.
 *
 * @param lastModified A date of last modification of a document
 * @param name A name of the file
 * @param URL An url to download a file
 */

data class SejmAttachmentDto(
    // A date of last modification of a document
    @Json(name = "lastModified")
    val lastModified: java.time.LocalDateTime? = null,
    // A name of the file
    @Json(name = "name")
    val name: kotlin.String? = null,
    // An url to download a file
    @Json(name = "URL")
    val URL: kotlin.String? = null,
)
