/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused",
)

package vote.fetcher.polishsejm.client.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 *
 *
 * Values: chairman,acting_chairman,deputy_chairman,co_chairman,vice_chairman,secretary,member,financial_auditor,presidium_member,spokesman,spokesperson,disciplinary_spokesman,treasurer
 */

@JsonClass(generateAdapter = false)
enum class SejmMemberTypeDto(val value: kotlin.String) {
    @Json(name = "chairman")
    chairman("chairman"),

    @Json(name = "acting_chairman")
    acting_chairman("acting_chairman"),

    @Json(name = "deputy_chairman")
    deputy_chairman("deputy_chairman"),

    @Json(name = "co_chairman")
    co_chairman("co_chairman"),

    @Json(name = "vice_chairman")
    vice_chairman("vice_chairman"),

    @Json(name = "secretary")
    secretary("secretary"),

    @Json(name = "member")
    member("member"),

    @Json(name = "financial_auditor")
    financial_auditor("financial_auditor"),

    @Json(name = "presidium_member")
    presidium_member("presidium_member"),

    @Json(name = "spokesman")
    spokesman("spokesman"),

    @Json(name = "spokesperson")
    spokesperson("spokesperson"),

    @Json(name = "disciplinary_spokesman")
    disciplinary_spokesman("disciplinary_spokesman"),

    @Json(name = "treasurer")
    treasurer("treasurer"),
    ;

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is SejmMemberTypeDto) "$data" else null

        /**
         * Returns a valid [SejmMemberTypeDto] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): SejmMemberTypeDto? =
            data?.let {
                val normalizedData = "$it".lowercase()
                entries.firstOrNull { value ->
                    it == value || normalizedData == "$value".lowercase()
                }
            }
    }
}
