/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused",
)

package vote.fetcher.polishsejm.client.models

import com.squareup.moshi.Json
import vote.fetcher.polishsejm.client.models.SejmVoteValueDto

/**
 * a vote
 *
 * @param MP an MP number
 * @param firstName an MP first name
 * @param lastName an MP last name
 * @param secondName an MP second name
 * @param club an MP club
 * @param vote a vote
 * @param listVotes a vote on a list
 * @param mP
 */

data class SejmVoteDto(
    // an MP number
    @Json(name = "MP")
    val _MP: kotlin.Int? = null,
    // an MP first name
    @Json(name = "firstName")
    val firstName: kotlin.String? = null,
    // an MP last name
    @Json(name = "lastName")
    val lastName: kotlin.String? = null,
    // an MP second name
    @Json(name = "secondName")
    val secondName: kotlin.String? = null,
    // an MP club
    @Json(name = "club")
    val club: kotlin.String? = null,
    // a vote
    @Json(name = "vote")
    val vote: SejmVoteValueDto? = null,
    // a vote on a list
    @Json(name = "listVotes")
    val listVotes: kotlin.collections.Map<kotlin.String, SejmVoteValueDto>? = null,
    @Json(name = "mP")
    val mP: kotlin.Int? = null,
)
