/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused",
)

package vote.fetcher.polishsejm.client.models

import com.squareup.moshi.Json

/**
 * voting option when voting on a list
 *
 * @param optionIndex an option index
 * @param option an option
 * @param description an optional description
 * @param votes number of votes for this option
 */

data class SejmVotingOptionDto(
    // an option index
    @Json(name = "optionIndex")
    val optionIndex: kotlin.Int? = null,
    // an option
    @Json(name = "option")
    val option: kotlin.String? = null,
    // an optional description
    @Json(name = "description")
    val description: kotlin.String? = null,
    // number of votes for this option
    @Json(name = "votes")
    val votes: kotlin.Int? = null,
)
