/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused",
)

package vote.fetcher.polishsejm.client.models

import com.squareup.moshi.Json

/**
 * a video
 *
 * @param unid An unique indentifier of a transmission
 * @param videoLink An URL or URLs to a video transmission
 * @param otherVideoLinks A list of URLs to a other cameras in a video transmission
 * @param videoMessagesLink A link to a messages for a transmission
 * @param type A type of transmission
 * @param transcribe Is there a transcription available
 * @param startDateTime A start date and time of transmission
 * @param endDateTime An end date and time of transmission
 * @param signLangLink An URL of a sign language transmission
 * @param title A title of a transmission
 * @param audio A link to a an audio file
 * @param room A room where the transmission takes place
 * @param description A description of a transmission
 * @param committee A committee code if the transmission is a committee meeting
 * @param subcommittee A subcommittee code if the transmission is a subcommittee meeting
 * @param playerLink A link to a video player on the Sejm website
 * @param playerLinkIFrame A link to a video player on the Sejm website, that can be embedded as iframe
 */

data class SejmVideoDto(
    // An unique indentifier of a transmission
    @Json(name = "unid")
    val unid: kotlin.String? = null,
    // An URL or URLs to a video transmission
    @Json(name = "videoLink")
    val videoLink: kotlin.String? = null,
    // A list of URLs to a other cameras in a video transmission
    @Json(name = "otherVideoLinks")
    val otherVideoLinks: kotlin.collections.List<kotlin.String>? = null,
    // A link to a messages for a transmission
    @Json(name = "videoMessagesLink")
    val videoMessagesLink: kotlin.String? = null,
    // A type of transmission
    @Json(name = "type")
    val type: kotlin.String? = null,
    // Is there a transcription available
    @Json(name = "transcribe")
    val transcribe: kotlin.Boolean? = null,
    // A start date and time of transmission
    @Json(name = "startDateTime")
    val startDateTime: java.time.LocalDateTime? = null,
    // An end date and time of transmission
    @Json(name = "endDateTime")
    val endDateTime: java.time.LocalDateTime? = null,
    // An URL of a sign language transmission
    @Json(name = "signLangLink")
    val signLangLink: kotlin.String? = null,
    // A title of a transmission
    @Json(name = "title")
    val title: kotlin.String? = null,
    // A link to a an audio file
    @Json(name = "audio")
    val audio: kotlin.String? = null,
    // A room where the transmission takes place
    @Json(name = "room")
    val room: kotlin.String? = null,
    // A description of a transmission
    @Json(name = "description")
    val description: kotlin.String? = null,
    // A committee code if the transmission is a committee meeting
    @Json(name = "committee")
    val committee: kotlin.String? = null,
    // A subcommittee code if the transmission is a subcommittee meeting
    @Json(name = "subcommittee")
    val subcommittee: kotlin.String? = null,
    // A link to a video player on the Sejm website
    @Json(name = "playerLink")
    val playerLink: kotlin.String? = null,
    // A link to a video player on the Sejm website, that can be embedded as iframe
    @Json(name = "playerLinkIFrame")
    val playerLinkIFrame: kotlin.String? = null,
)
