/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused",
)

package vote.fetcher.polishsejm.client.models

import com.squareup.moshi.Json
import vote.fetcher.polishsejm.client.models.SejmVotingKindDto
import vote.fetcher.polishsejm.client.models.SejmVotingMajorityDto
import vote.fetcher.polishsejm.client.models.SejmVotingOptionDto

/**
 * a voting
 *
 * @param yes number of 'yes' votes
 * @param no number of 'no' votes
 * @param abstain number of 'abstain' votes
 * @param present number of 'present' votes in quorum voting
 * @param notParticipating number of people who did not vote
 * @param totalVoted number of people who voted
 * @param term a Sejm term
 * @param sitting a Sejm sitting number
 * @param sittingDay a day of Sejm sitting
 * @param votingNumber a voting number
 * @param date a voting date and time
 * @param title a voting title
 * @param description description
 * @param topic a voting topic
 * @param kind a kind of voting
 * @param majorityType a voting majority
 * @param majorityVotes number of votes that constitute a majority
 * @param votingOptions a list of options when voting on a list
 * @param links Links
 * @param againstAll number of votes against all options when voting on list
 */

data class SejmVotingDto(
    // number of 'yes' votes
    @Json(name = "yes")
    val yes: kotlin.Int? = null,
    // number of 'no' votes
    @Json(name = "no")
    val no: kotlin.Int? = null,
    // number of 'abstain' votes
    @Json(name = "abstain")
    val abstain: kotlin.Int? = null,
    // number of 'present' votes in quorum voting
    @Json(name = "present")
    val present: kotlin.Int? = null,
    // number of people who did not vote
    @Json(name = "notParticipating")
    val notParticipating: kotlin.Int? = null,
    // number of people who voted
    @Json(name = "totalVoted")
    val totalVoted: kotlin.Int? = null,
    // a Sejm term
    @Json(name = "term")
    val term: kotlin.Int? = null,
    // a Sejm sitting number
    @Json(name = "sitting")
    val sitting: kotlin.Int? = null,
    // a day of Sejm sitting
    @Json(name = "sittingDay")
    val sittingDay: kotlin.Int? = null,
    // a voting number
    @Json(name = "votingNumber")
    val votingNumber: kotlin.Int? = null,
    // a voting date and time
    @Json(name = "date")
    val date: java.time.LocalDateTime? = null,
    // a voting title
    @Json(name = "title")
    val title: kotlin.String? = null,
    // description
    @Json(name = "description")
    val description: kotlin.String? = null,
    // a voting topic
    @Json(name = "topic")
    val topic: kotlin.String? = null,
    // a kind of voting
    @Json(name = "kind")
    val kind: SejmVotingKindDto? = null,
    // a voting majority
    @Json(name = "majorityType")
    val majorityType: SejmVotingMajorityDto? = null,
    // number of votes that constitute a majority
    @Json(name = "majorityVotes")
    val majorityVotes: kotlin.Int? = null,
    // a list of options when voting on a list
    @Json(name = "votingOptions")
    val votingOptions: kotlin.collections.List<SejmVotingOptionDto>? = null,
    // Links
    @Json(name = "links")
    val links: kotlin.collections.List<kotlin.Any?>? = null,
    // number of votes against all options when voting on list
    @Json(name = "againstAll")
    val againstAll: kotlin.Int? = null,
)
