/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused",
)

package vote.fetcher.polishsejm.client.models

import com.squareup.moshi.Json
import vote.fetcher.polishsejm.client.models.SejmComitteeTypeDto
import vote.fetcher.polishsejm.client.models.SejmMemberDto

/**
 * A comittee.
 *
 * @param code Code of committee
 * @param name Name of the committee
 * @param nameGenitive Name of the committee in genitive
 * @param type Type of the committee
 * @param phone Phone of the committee
 * @param appointmentDate Date of appointment
 * @param compositionDate Date of composition
 * @param dismissalDate Date of dismissal of the committee
 * @param scope Description of the committee
 * @param members a list of committee members (current or at the date of closing the committee)
 * @param subCommittees
 */

data class SejmCommitteeDto(
    // Code of committee
    @Json(name = "code")
    val code: kotlin.String? = null,
    // Name of the committee
    @Json(name = "name")
    val name: kotlin.String? = null,
    // Name of the committee in genitive
    @Json(name = "nameGenitive")
    val nameGenitive: kotlin.String? = null,
    // Type of the committee
    @Json(name = "type")
    val type: SejmComitteeTypeDto? = null,
    // Phone of the committee
    @Json(name = "phone")
    val phone: kotlin.String? = null,
    // Date of appointment
    @Json(name = "appointmentDate")
    val appointmentDate: java.time.LocalDate? = null,
    // Date of composition
    @Json(name = "compositionDate")
    val compositionDate: java.time.LocalDate? = null,
    // Date of dismissal of the committee
    @Json(name = "dismissalDate")
    val dismissalDate: java.time.LocalDate? = null,
    // Description of the committee
    @Json(name = "scope")
    val scope: kotlin.String? = null,
    // a list of committee members (current or at the date of closing the committee)
    @Json(name = "members")
    val members: kotlin.collections.List<SejmMemberDto>? = null,
    @Json(name = "subCommittees")
    val subCommittees: kotlin.collections.List<kotlin.String>? = null,
)
