/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused",
)

package vote.fetcher.polishsejm.client.models

import com.squareup.moshi.Json

/**
 * Details about a Member of Parliament.
 *
 * @param id A number of the identity card of the MP.
 * @param firstLastName The first and last name of the MP.
 * @param lastFirstName The last and first name of the MP.
 * @param firstName The first name of the MP.
 * @param secondName The second name of the MP.
 * @param lastName The last name of the MP.
 * @param genitiveName The first and last name in genitive case.
 * @param accusativeName The first and last name in accusative case.
 * @param email The email of the MP.
 * @param active Is the MP active?
 * @param inactiveCause The cause of inactivity
 * @param waiverDesc ?
 * @param districtNum A district id where MP was elected
 * @param districtName A district name where MP was elected
 * @param voivodeship A voivodeship where MP was elected
 * @param club A club to where MP is belonging
 * @param birthDate a date of birth
 * @param birthLocation a place of birth
 * @param profession a profession
 * @param educationLevel an education level
 * @param numberOfVotes a number of votes
 */

data class SejmMPDto(
    // A number of the identity card of the MP.
    @Json(name = "id")
    val id: kotlin.Int? = null,
    // The first and last name of the MP.
    @Json(name = "firstLastName")
    val firstLastName: kotlin.String? = null,
    // The last and first name of the MP.
    @Json(name = "lastFirstName")
    val lastFirstName: kotlin.String? = null,
    // The first name of the MP.
    @Json(name = "firstName")
    val firstName: kotlin.String? = null,
    // The second name of the MP.
    @Json(name = "secondName")
    val secondName: kotlin.String? = null,
    // The last name of the MP.
    @Json(name = "lastName")
    val lastName: kotlin.String? = null,
    // The first and last name in genitive case.
    @Json(name = "genitiveName")
    val genitiveName: kotlin.String? = null,
    // The first and last name in accusative case.
    @Json(name = "accusativeName")
    val accusativeName: kotlin.String? = null,
    // The email of the MP.
    @Json(name = "email")
    val email: kotlin.String? = null,
    // Is the MP active?
    @Json(name = "active")
    val active: kotlin.Boolean? = null,
    // The cause of inactivity
    @Json(name = "inactiveCause")
    val inactiveCause: kotlin.String? = null,
    // ?
    @Json(name = "waiverDesc")
    val waiverDesc: kotlin.String? = null,
    // A district id where MP was elected
    @Json(name = "districtNum")
    val districtNum: kotlin.Int? = null,
    // A district name where MP was elected
    @Json(name = "districtName")
    val districtName: kotlin.String? = null,
    // A voivodeship where MP was elected
    @Json(name = "voivodeship")
    val voivodeship: kotlin.String? = null,
    // A club to where MP is belonging
    @Json(name = "club")
    val club: kotlin.String? = null,
    // a date of birth
    @Json(name = "birthDate")
    val birthDate: java.time.LocalDate? = null,
    // a place of birth
    @Json(name = "birthLocation")
    val birthLocation: kotlin.String? = null,
    // a profession
    @Json(name = "profession")
    val profession: kotlin.String? = null,
    // an education level
    @Json(name = "educationLevel")
    val educationLevel: kotlin.String? = null,
    // a number of votes
    @Json(name = "numberOfVotes")
    val numberOfVotes: kotlin.Int? = null,
)
