/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused",
)

package vote.fetcher.polishsejm.client.models

import com.squareup.moshi.Json

/**
 * A print
 *
 * @param term a Sejm term
 * @param number a number of a print in the specified Sejm term
 * @param numberAssociated numbers of prints that this print is associated with
 * @param title a title of a print
 * @param documentDate a date of a print
 * @param deliveryDate a date of delivery of a print
 * @param processPrint a list of prints that started a legislative process that this print is connected to
 * @param changeDate a date of of last change to the print
 * @param attachments a list of attachments added to the print
 * @param additionalPrints a list of additional prints added to the print
 */

data class SejmPrintDto(
    // a Sejm term
    @Json(name = "term")
    val term: kotlin.Int? = null,
    // a number of a print in the specified Sejm term
    @Json(name = "number")
    val number: kotlin.String? = null,
    // numbers of prints that this print is associated with
    @Json(name = "numberAssociated")
    val numberAssociated: kotlin.collections.List<kotlin.String>? = null,
    // a title of a print
    @Json(name = "title")
    val title: kotlin.String? = null,
    // a date of a print
    @Json(name = "documentDate")
    val documentDate: java.time.LocalDate? = null,
    // a date of delivery of a print
    @Json(name = "deliveryDate")
    val deliveryDate: java.time.LocalDate? = null,
    // a list of prints that started a legislative process that this print is connected to
    @Json(name = "processPrint")
    val processPrint: kotlin.collections.List<kotlin.String>? = null,
    // a date of of last change to the print
    @Json(name = "changeDate")
    val changeDate: java.time.LocalDateTime? = null,
    // a list of attachments added to the print
    @Json(name = "attachments")
    val attachments: kotlin.collections.List<kotlin.String>? = null,
    // a list of additional prints added to the print
    @Json(name = "additionalPrints")
    val additionalPrints: kotlin.collections.List<SejmPrintDto>? = null,
)
