/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused",
)

package vote.fetcher.polishsejm.client.models

import com.squareup.moshi.Json
import vote.fetcher.polishsejm.client.models.SejmMemberTypeDto

/**
 * Information about a member of a group
 *
 * @param id A number of the identity card of the MP
 * @param name Last and first name of the MP
 * @param club Name of a club
 * @param senator A flag indicating that a member is not an MP, but a senate member
 * @param type A type of membership
 * @param membershipStart A date when membership in this group started
 * @param membershipEnd A date when membership in this group ended
 * @param mandateEnd A date when mandate of MP expired
 */

data class SejmGroupMemberDto(
    // A number of the identity card of the MP
    @Json(name = "id")
    val id: kotlin.String? = null,
    // Last and first name of the MP
    @Json(name = "name")
    val name: kotlin.String? = null,
    // Name of a club
    @Json(name = "club")
    val club: kotlin.String? = null,
    // A flag indicating that a member is not an MP, but a senate member
    @Json(name = "senator")
    val senator: kotlin.Boolean? = null,
    // A type of membership
    @Json(name = "type")
    val type: SejmMemberTypeDto? = null,
    // A date when membership in this group started
    @Json(name = "membershipStart")
    val membershipStart: java.time.LocalDate? = null,
    // A date when membership in this group ended
    @Json(name = "membershipEnd")
    val membershipEnd: java.time.LocalDate? = null,
    // A date when mandate of MP expired
    @Json(name = "mandateEnd")
    val mandateEnd: java.time.LocalDate? = null,
)
