/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused",
)

package vote.fetcher.polishsejm.client.models

import com.squareup.moshi.Json
import vote.fetcher.polishsejm.client.models.SejmProcessStageDto

/**
 * the President motion (veto or remove inconsistency with the constitution)
 *
 * @param stageName a name of a stage
 * @param date a stage date
 * @param children child stages
 * @param printNumber print number of President's motion
 * @param comment comment
 * @param govermentPositionDate date of the goverment position
 * @param stageType
 */

data class SejmProcessStageVetoDto(
    // a name of a stage
    @Json(name = "stageName")
    val stageName: kotlin.String? = null,
    // a stage date
    @Json(name = "date")
    val date: java.time.LocalDate? = null,
    // child stages
    @Json(name = "children")
    val children: kotlin.collections.List<SejmProcessStageDto>? = null,
    // print number of President's motion
    @Json(name = "printNumber")
    val printNumber: kotlin.String? = null,
    // comment
    @Json(name = "comment")
    val comment: kotlin.String? = null,
    // date of the goverment position
    @Json(name = "govermentPositionDate")
    val govermentPositionDate: java.time.LocalDate? = null,
    @Json(name = "stageType")
    val stageType: kotlin.String? = null,
)
