/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused",
)

package vote.fetcher.polishsejm.client.models

import com.squareup.moshi.Json
import vote.fetcher.polishsejm.client.models.SejmProcessTypeDto
import vote.fetcher.polishsejm.client.models.SejmUEStatusDto
import vote.fetcher.polishsejm.client.models.SejmUrgencyStatusDto

/**
 * A legislative process
 *
 * @param uE is this process realization of the UE law
 * @param eLI an European Legislation Identifier
 * @param term A Sejm term
 * @param number A number of the process
 * @param title A title of the process
 * @param titleFinal A final title of the act
 * @param description A description of the process
 * @param ue A UE type of process
 * @param documentDate A date of document
 * @param processStartDate Process start date
 * @param changeDate A date when a process was last changed
 * @param documentType A document type
 * @param documentTypeEnum A document type
 * @param comments Comments
 * @param webGeneratedDate A date when a web page with a process was updated
 * @param closureDate A date of case closure
 * @param address an address of publication in the ISAP service. An address is in format {publisher}{year}{volume}{position}
 * @param displayAddress an address to display
 * @param ELI an European Legislation Identifier
 * @param passed is this act was passed
 * @param links Links
 * @param shortenProcedure Article 51 of the Sejm Regulations - in particularly justified cases, the Sejm may shorten the procedure for drafting bills
 * @param urgencyStatus urgency status
 * @param urgencyWithdrawDate date when urgency clause was withdrawn
 * @param printsConsideredJointly prints considered jointly
 */

data class SejmProcessHeaderDto(
    // is this process realization of the UE law
    @Json(name = "uE")
    val uE: SejmUEStatusDto? = null,
    // an European Legislation Identifier
    @Json(name = "eLI")
    val eLI: kotlin.String? = null,
    // A Sejm term
    @Json(name = "term")
    val term: kotlin.Int? = null,
    // A number of the process
    @Json(name = "number")
    val number: kotlin.String? = null,
    // A title of the process
    @Json(name = "title")
    val title: kotlin.String? = null,
    // A final title of the act
    @Json(name = "titleFinal")
    val titleFinal: kotlin.String? = null,
    // A description of the process
    @Json(name = "description")
    val description: kotlin.String? = null,
    // A UE type of process
    @Json(name = "ue")
    val ue: SejmUEStatusDto? = null,
    // A date of document
    @Json(name = "documentDate")
    val documentDate: java.time.LocalDate? = null,
    // Process start date
    @Json(name = "processStartDate")
    val processStartDate: java.time.LocalDate? = null,
    // A date when a process was last changed
    @Json(name = "changeDate")
    val changeDate: java.time.LocalDateTime? = null,
    // A document type
    @Json(name = "documentType")
    val documentType: kotlin.String? = null,
    // A document type
    @Json(name = "documentTypeEnum")
    val documentTypeEnum: SejmProcessTypeDto? = null,
    // Comments
    @Json(name = "comments")
    val comments: kotlin.String? = null,
    // A date when a web page with a process was updated
    @Json(name = "webGeneratedDate")
    val webGeneratedDate: java.time.LocalDateTime? = null,
    // A date of case closure
    @Json(name = "closureDate")
    val closureDate: java.time.LocalDate? = null,
    // an address of publication in the ISAP service. An address is in format {publisher}{year}{volume}{position}
    @Json(name = "address")
    val address: kotlin.String? = null,
    // an address to display
    @Json(name = "displayAddress")
    val displayAddress: kotlin.String? = null,
    // an European Legislation Identifier
    @Json(name = "ELI")
    val _ELI: kotlin.String? = null,
    // is this act was passed
    @Json(name = "passed")
    val passed: kotlin.Boolean? = null,
    // Links
    @Json(name = "links")
    val links: kotlin.collections.List<kotlin.Any?>? = null,
    // Article 51 of the Sejm Regulations - in particularly justified cases, the Sejm may shorten the procedure for drafting bills
    @Json(name = "shortenProcedure")
    val shortenProcedure: kotlin.Boolean? = null,
    // urgency status
    @Json(name = "urgencyStatus")
    val urgencyStatus: SejmUrgencyStatusDto? = null,
    // date when urgency clause was withdrawn
    @Json(name = "urgencyWithdrawDate")
    val urgencyWithdrawDate: java.time.LocalDate? = null,
    // prints considered jointly
    @Json(name = "printsConsideredJointly")
    val printsConsideredJointly: kotlin.collections.Set<kotlin.String>? = null,
)
