/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused",
)

package vote.fetcher.polishsejm.client.models

import com.squareup.moshi.Json

/**
 * info about prints
 *
 * @param count number of prints
 * @param lastChanged date of last changed document
 * @param link a link to prints endpoint
 */

data class SejmPrintInfoDto(
    // number of prints
    @Json(name = "count")
    val count: kotlin.Int? = null,
    // date of last changed document
    @Json(name = "lastChanged")
    val lastChanged: java.time.LocalDateTime? = null,
    // a link to prints endpoint
    @Json(name = "link")
    val link: kotlin.String? = null,
)
