/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused",
)

package vote.fetcher.polishsejm.client.models

import com.squareup.moshi.Json
import vote.fetcher.polishsejm.client.models.SejmProcessDocumentDto
import vote.fetcher.polishsejm.client.models.SejmProcessStageDto
import vote.fetcher.polishsejm.client.models.SejmProcessTypeDto
import vote.fetcher.polishsejm.client.models.SejmUEStatusDto
import vote.fetcher.polishsejm.client.models.SejmUrgencyStatusDto

/**
 * A details of legislative process
 *
 * @param term a Sejm term
 * @param number a number of a print in the specified Sejm term
 * @param title a title of a process
 * @param description a description of a process
 * @param uE is this process realization of the UE law
 * @param documentDate a date of a print
 * @param changeDate a date of last change to the process
 * @param webGeneratedDate A date when a web page with a process was updated
 * @param processStartDate a date of the start of the process
 * @param documentType a type of a document
 * @param documentTypeEnum A document type
 * @param comments comments
 * @param printsConsideredJointly prints considered jointly
 * @param titleFinal A final title of the act
 * @param closureDate A date of case closure
 * @param address an address of publication in the ISAP service. An address is in format {publisher}{year}{volume}{position}
 * @param displayAddress an address to display
 * @param eLI an European Legislation Identifier
 * @param passed is this act was passed
 * @param links Links
 * @param shortenProcedure Article 51 of the Sejm Regulations - in particularly justified cases, the Sejm may shorten the procedure for drafting bills
 * @param urgencyStatus urgency status
 * @param urgencyWithdrawDate date when urgency clause was withdrawn
 * @param otherDocuments other prints, corrections
 * @param rclNum number from government part of the process (from RCL website)
 * @param rclLink link to government part of the process (RCL website)
 * @param legislativeCommittee indicates that for work on this project a members of Legislative Committee has been assigned
 * @param principleOfSubsidiarity indicates that the project is inconsistent with the principle of subsidiarity
 * @param stages stages of the process
 */

data class SejmProcessDetailsDto(
    // a Sejm term
    @Json(name = "term")
    val term: kotlin.Int? = null,
    // a number of a print in the specified Sejm term
    @Json(name = "number")
    val number: kotlin.String? = null,
    // a title of a process
    @Json(name = "title")
    val title: kotlin.String? = null,
    // a description of a process
    @Json(name = "description")
    val description: kotlin.String? = null,
    // is this process realization of the UE law
    @Json(name = "uE")
    val uE: SejmUEStatusDto? = null,
    // a date of a print
    @Json(name = "documentDate")
    val documentDate: java.time.LocalDate? = null,
    // a date of last change to the process
    @Json(name = "changeDate")
    val changeDate: java.time.LocalDateTime? = null,
    // A date when a web page with a process was updated
    @Json(name = "webGeneratedDate")
    val webGeneratedDate: java.time.LocalDateTime? = null,
    // a date of the start of the process
    @Json(name = "processStartDate")
    val processStartDate: java.time.LocalDate? = null,
    // a type of a document
    @Json(name = "documentType")
    val documentType: kotlin.String? = null,
    // A document type
    @Json(name = "documentTypeEnum")
    val documentTypeEnum: SejmProcessTypeDto? = null,
    // comments
    @Json(name = "comments")
    val comments: kotlin.String? = null,
    // prints considered jointly
    @Json(name = "printsConsideredJointly")
    val printsConsideredJointly: kotlin.collections.Set<kotlin.String>? = null,
    // A final title of the act
    @Json(name = "titleFinal")
    val titleFinal: kotlin.String? = null,
    // A date of case closure
    @Json(name = "closureDate")
    val closureDate: java.time.LocalDate? = null,
    // an address of publication in the ISAP service. An address is in format {publisher}{year}{volume}{position}
    @Json(name = "address")
    val address: kotlin.String? = null,
    // an address to display
    @Json(name = "displayAddress")
    val displayAddress: kotlin.String? = null,
    // an European Legislation Identifier
    @Json(name = "eLI")
    val eLI: kotlin.String? = null,
    // is this act was passed
    @Json(name = "passed")
    val passed: kotlin.Boolean? = null,
    // Links
    @Json(name = "links")
    val links: kotlin.collections.List<kotlin.Any?>? = null,
    // Article 51 of the Sejm Regulations - in particularly justified cases, the Sejm may shorten the procedure for drafting bills
    @Json(name = "shortenProcedure")
    val shortenProcedure: kotlin.Boolean? = null,
    // urgency status
    @Json(name = "urgencyStatus")
    val urgencyStatus: SejmUrgencyStatusDto? = null,
    // date when urgency clause was withdrawn
    @Json(name = "urgencyWithdrawDate")
    val urgencyWithdrawDate: java.time.LocalDate? = null,
    // other prints, corrections
    @Json(name = "otherDocuments")
    val otherDocuments: kotlin.collections.List<SejmProcessDocumentDto>? = null,
    // number from government part of the process (from RCL website)
    @Json(name = "rclNum")
    val rclNum: kotlin.String? = null,
    // link to government part of the process (RCL website)
    @Json(name = "rclLink")
    val rclLink: kotlin.String? = null,
    // indicates that for work on this project a members of Legislative Committee has been assigned
    @Json(name = "legislativeCommittee")
    val legislativeCommittee: kotlin.Boolean? = null,
    // indicates that the project is inconsistent with the principle of subsidiarity
    @Json(name = "principleOfSubsidiarity")
    val principleOfSubsidiarity: kotlin.Boolean? = null,
    // stages of the process
    @Json(name = "stages")
    val stages: kotlin.collections.List<SejmProcessStageDto>? = null,
)
