/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused",
)

package vote.fetcher.polishsejm.client.models

import com.squareup.moshi.Json
import vote.fetcher.polishsejm.client.models.SejmApplicantTypeDto
import vote.fetcher.polishsejm.client.models.SejmBillStatusDto
import vote.fetcher.polishsejm.client.models.SejmBillTypeDto

/**
 * A bill or a draft resolution submitted to the Sejm
 *
 * @param term Sejm term (parliamentary term)
 * @param number Internal Sejm document number
 * @param sendersNumber External sender number assigned by KPRM or other authority
 * @param print Sejm print number
 * @param title Title of the bill or draft resolution
 * @param submissionType Submission type of the document
 * @param dateOfReceipt Date when the document was received by the Sejm
 * @param description Short description or justification of the document
 * @param status Current procedural status of the document
 * @param euRelated Whether this project aims to implement European Union law
 * @param withdrawnDate Date when the document was withdrawn, if applicable
 * @param publicConsultation Indicates whether the document was sent to public consultation
 * @param publicConsultationStartDate Date when public consultation started
 * @param publicConsultationEndDate Date when public consultation ended
 * @param consultationResults Indicates whether consultation results are available
 * @param applicantType Entity that submitted the bill
 */

data class SejmBillDetailsDto(
    // Sejm term (parliamentary term)
    @Json(name = "term")
    val term: kotlin.Int? = null,
    // Internal Sejm document number
    @Json(name = "number")
    val number: kotlin.String? = null,
    // External sender number assigned by KPRM or other authority
    @Json(name = "sendersNumber")
    val sendersNumber: kotlin.String? = null,
    // Sejm print number
    @Json(name = "print")
    val print: kotlin.String? = null,
    // Title of the bill or draft resolution
    @Json(name = "title")
    val title: kotlin.String? = null,
    // Submission type of the document
    @Json(name = "submissionType")
    val submissionType: SejmBillTypeDto? = null,
    // Date when the document was received by the Sejm
    @Json(name = "dateOfReceipt")
    val dateOfReceipt: java.time.LocalDate? = null,
    // Short description or justification of the document
    @Json(name = "description")
    val description: kotlin.String? = null,
    // Current procedural status of the document
    @Json(name = "status")
    val status: SejmBillStatusDto? = null,
    // Whether this project aims to implement European Union law
    @Json(name = "euRelated")
    val euRelated: kotlin.Boolean? = null,
    // Date when the document was withdrawn, if applicable
    @Json(name = "withdrawnDate")
    val withdrawnDate: java.time.LocalDate? = null,
    // Indicates whether the document was sent to public consultation
    @Json(name = "publicConsultation")
    val publicConsultation: kotlin.Boolean? = null,
    // Date when public consultation started
    @Json(name = "publicConsultationStartDate")
    val publicConsultationStartDate: java.time.LocalDate? = null,
    // Date when public consultation ended
    @Json(name = "publicConsultationEndDate")
    val publicConsultationEndDate: java.time.LocalDate? = null,
    // Indicates whether consultation results are available
    @Json(name = "consultationResults")
    val consultationResults: kotlin.Boolean? = null,
    // Entity that submitted the bill
    @Json(name = "applicantType")
    val applicantType: SejmApplicantTypeDto? = null,
)
