/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused",
)

package vote.fetcher.polishsejm.client.models

import com.squareup.moshi.Json
import vote.fetcher.polishsejm.client.models.SejmProcessStageDto

/**
 * The Constitutional Tribunal ruling
 *
 * @param stageName a name of a stage
 * @param date a stage date
 * @param children child stages
 * @param publisher a code of a publisher
 * @param publicationYear a year of publication
 * @param publicationNumber a volume of a publication. Specifies a volume in year. After year 2012 there are no volumes and this field should have value '0'.
 * @param publicationPosition a position in a year
 * @param verdict a Constitutional Tribunal verdict
 * @param links Links to HTML pages
 * @param stageType
 */

data class SejmProcessStageConstitutionalTribunalRulingDto(
    // a name of a stage
    @Json(name = "stageName")
    val stageName: kotlin.String? = null,
    // a stage date
    @Json(name = "date")
    val date: java.time.LocalDate? = null,
    // child stages
    @Json(name = "children")
    val children: kotlin.collections.List<SejmProcessStageDto>? = null,
    // a code of a publisher
    @Json(name = "publisher")
    val publisher: kotlin.String? = null,
    // a year of publication
    @Json(name = "publicationYear")
    val publicationYear: kotlin.String? = null,
    // a volume of a publication. Specifies a volume in year. After year 2012 there are no volumes and this field should have value '0'.
    @Json(name = "publicationNumber")
    val publicationNumber: kotlin.String? = null,
    // a position in a year
    @Json(name = "publicationPosition")
    val publicationPosition: kotlin.String? = null,
    // a Constitutional Tribunal verdict
    @Json(name = "verdict")
    val verdict: kotlin.String? = null,
    // Links to HTML pages
    @Json(name = "links")
    val links: kotlin.collections.List<kotlin.Any?>? = null,
    @Json(name = "stageType")
    val stageType: kotlin.String? = null,
)
