/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused",
)

package vote.fetcher.polishsejm.client.apis

import okhttp3.Call
import okhttp3.HttpUrl
import vote.fetcher.polishsejm.client.infrastructure.ApiClient
import vote.fetcher.polishsejm.client.infrastructure.ApiResponse
import vote.fetcher.polishsejm.client.infrastructure.ClientError
import vote.fetcher.polishsejm.client.infrastructure.ClientException
import vote.fetcher.polishsejm.client.infrastructure.MultiValueMap
import vote.fetcher.polishsejm.client.infrastructure.RequestConfig
import vote.fetcher.polishsejm.client.infrastructure.RequestMethod
import vote.fetcher.polishsejm.client.infrastructure.ResponseType
import vote.fetcher.polishsejm.client.infrastructure.ServerError
import vote.fetcher.polishsejm.client.infrastructure.ServerException
import vote.fetcher.polishsejm.client.infrastructure.Success
import vote.fetcher.polishsejm.client.models.SejmBillDto
import vote.fetcher.polishsejm.client.models.SejmBillStatusDto
import vote.fetcher.polishsejm.client.models.SejmBillTypeDto
import java.io.IOException

open class BillsApi(basePath: kotlin.String = defaultBasePath, client: Call.Factory = ApiClient.defaultClient) : ApiClient(
    basePath,
    client,
) {
    companion object {
        @JvmStatic
        val defaultBasePath: String by lazy {
            System.getProperties().getProperty(ApiClient.BASE_URL_KEY, "https://api.sejm.gov.pl")
        }
    }

    /**
     * GET /sejm/term{term}/bills
     * Returns a list of bills
     *
     * @param term a Sejm term
     * @param consultationResults filter only bills with consultation results (optional)
     * @param dateOfReceiptFrom filter bills received after date (optional)
     * @param dateOfReceiptTo filter bills received before date (optional)
     * @param euRelated filter bills aimed at implementing European Union law (optional)
     * @param limit controls the maximum number of items that may be returned for a single request (optional, default to 50)
     * @param offset controls the starting point within the collection of resource results (optional, default to 0)
     * @param print filter by print number (optional)
     * @param publicConsultation filter only bills with public consultation (optional)
     * @param sort sorts objects by specified field, to sort in descending order add a minus sign before field name (optional)
     * @param sortBy sorts objects by specified field, to sort in descending order add a minus sign before field name (optional)
     * @param status filter by status (optional)
     * @param submissionType filter bills or resolutions (optional)
     * @param title filter by part of a title (optional)
     * @return kotlin.collections.List<SejmBillDto>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(
        IllegalStateException::class,
        IOException::class,
        UnsupportedOperationException::class,
        ClientException::class,
        ServerException::class,
    )
    fun sejmTermtermBillsGet(
        term: kotlin.Int,
        consultationResults: kotlin.Boolean? = null,
        dateOfReceiptFrom: java.time.LocalDate? = null,
        dateOfReceiptTo: java.time.LocalDate? = null,
        euRelated: kotlin.Boolean? = null,
        limit: kotlin.Int? = 50,
        offset: kotlin.Int? = 0,
        print: kotlin.String? = null,
        publicConsultation: kotlin.Boolean? = null,
        sort: kotlin.String? = null,
        sortBy: kotlin.String? = null,
        status: SejmBillStatusDto? = null,
        submissionType: SejmBillTypeDto? = null,
        title: kotlin.String? = null,
    ): kotlin.collections.List<SejmBillDto> {
        val localVarResponse =
            sejmTermtermBillsGetWithHttpInfo(
                term = term,
                consultationResults = consultationResults,
                dateOfReceiptFrom = dateOfReceiptFrom,
                dateOfReceiptTo = dateOfReceiptTo,
                euRelated = euRelated,
                limit = limit,
                offset = offset,
                print = print,
                publicConsultation = publicConsultation,
                sort = sort,
                sortBy = sortBy,
                status = status,
                submissionType = submissionType,
                title = title,
            )

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as kotlin.collections.List<SejmBillDto>
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException(
                    "Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}",
                    localVarError.statusCode,
                    localVarResponse,
                )
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException(
                    "Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}",
                    localVarError.statusCode,
                    localVarResponse,
                )
            }
        }
    }

    /**
     * GET /sejm/term{term}/bills
     * Returns a list of bills
     *
     * @param term a Sejm term
     * @param consultationResults filter only bills with consultation results (optional)
     * @param dateOfReceiptFrom filter bills received after date (optional)
     * @param dateOfReceiptTo filter bills received before date (optional)
     * @param euRelated filter bills aimed at implementing European Union law (optional)
     * @param limit controls the maximum number of items that may be returned for a single request (optional, default to 50)
     * @param offset controls the starting point within the collection of resource results (optional, default to 0)
     * @param print filter by print number (optional)
     * @param publicConsultation filter only bills with public consultation (optional)
     * @param sort sorts objects by specified field, to sort in descending order add a minus sign before field name (optional)
     * @param sortBy sorts objects by specified field, to sort in descending order add a minus sign before field name (optional)
     * @param status filter by status (optional)
     * @param submissionType filter bills or resolutions (optional)
     * @param title filter by part of a title (optional)
     * @return ApiResponse<kotlin.collections.List<SejmBillDto>?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun sejmTermtermBillsGetWithHttpInfo(
        term: kotlin.Int,
        consultationResults: kotlin.Boolean?,
        dateOfReceiptFrom: java.time.LocalDate?,
        dateOfReceiptTo: java.time.LocalDate?,
        euRelated: kotlin.Boolean?,
        limit: kotlin.Int?,
        offset: kotlin.Int?,
        print: kotlin.String?,
        publicConsultation: kotlin.Boolean?,
        sort: kotlin.String?,
        sortBy: kotlin.String?,
        status: SejmBillStatusDto?,
        submissionType: SejmBillTypeDto?,
        title: kotlin.String?,
    ): ApiResponse<kotlin.collections.List<SejmBillDto>?> {
        val localVariableConfig =
            sejmTermtermBillsGetRequestConfig(
                term = term,
                consultationResults = consultationResults,
                dateOfReceiptFrom = dateOfReceiptFrom,
                dateOfReceiptTo = dateOfReceiptTo,
                euRelated = euRelated,
                limit = limit,
                offset = offset,
                print = print,
                publicConsultation = publicConsultation,
                sort = sort,
                sortBy = sortBy,
                status = status,
                submissionType = submissionType,
                title = title,
            )

        return request<Unit, kotlin.collections.List<SejmBillDto>>(
            localVariableConfig,
        )
    }

    /**
     * To obtain the request config of the operation sejmTermtermBillsGet
     *
     * @param term a Sejm term
     * @param consultationResults filter only bills with consultation results (optional)
     * @param dateOfReceiptFrom filter bills received after date (optional)
     * @param dateOfReceiptTo filter bills received before date (optional)
     * @param euRelated filter bills aimed at implementing European Union law (optional)
     * @param limit controls the maximum number of items that may be returned for a single request (optional, default to 50)
     * @param offset controls the starting point within the collection of resource results (optional, default to 0)
     * @param print filter by print number (optional)
     * @param publicConsultation filter only bills with public consultation (optional)
     * @param sort sorts objects by specified field, to sort in descending order add a minus sign before field name (optional)
     * @param sortBy sorts objects by specified field, to sort in descending order add a minus sign before field name (optional)
     * @param status filter by status (optional)
     * @param submissionType filter bills or resolutions (optional)
     * @param title filter by part of a title (optional)
     * @return RequestConfig
     */
    fun sejmTermtermBillsGetRequestConfig(
        term: kotlin.Int,
        consultationResults: kotlin.Boolean?,
        dateOfReceiptFrom: java.time.LocalDate?,
        dateOfReceiptTo: java.time.LocalDate?,
        euRelated: kotlin.Boolean?,
        limit: kotlin.Int?,
        offset: kotlin.Int?,
        print: kotlin.String?,
        publicConsultation: kotlin.Boolean?,
        sort: kotlin.String?,
        sortBy: kotlin.String?,
        status: SejmBillStatusDto?,
        submissionType: SejmBillTypeDto?,
        title: kotlin.String?,
    ): RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
            .apply {
                if (consultationResults != null) {
                    put("consultationResults", listOf(consultationResults.toString()))
                }
                if (dateOfReceiptFrom != null) {
                    put("dateOfReceiptFrom", listOf(parseDateToQueryString<java.time.LocalDate>(dateOfReceiptFrom)))
                }
                if (dateOfReceiptTo != null) {
                    put("dateOfReceiptTo", listOf(parseDateToQueryString<java.time.LocalDate>(dateOfReceiptTo)))
                }
                if (euRelated != null) {
                    put("euRelated", listOf(euRelated.toString()))
                }
                if (limit != null) {
                    put("limit", listOf(limit.toString()))
                }
                if (offset != null) {
                    put("offset", listOf(offset.toString()))
                }
                if (print != null) {
                    put("print", listOf(print.toString()))
                }
                if (publicConsultation != null) {
                    put("publicConsultation", listOf(publicConsultation.toString()))
                }
                if (sort != null) {
                    put("sort", listOf(sort.toString()))
                }
                if (sortBy != null) {
                    put("sort_by", listOf(sortBy.toString()))
                }
                if (status != null) {
                    put("status", listOf(status.toString()))
                }
                if (submissionType != null) {
                    put("submissionType", listOf(submissionType.toString()))
                }
                if (title != null) {
                    put("title", listOf(title.toString()))
                }
            }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/sejm/term{term}/bills".replace("{" + "term" + "}", encodeURIComponent(term.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            body = localVariableBody,
        )
    }

    private fun encodeURIComponent(uriComponent: kotlin.String): kotlin.String =
        HttpUrl
            .Builder()
            .scheme("http")
            .host("localhost")
            .addPathSegment(uriComponent)
            .build()
            .encodedPathSegments[0]
}
