/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused",
)

package vote.fetcher.polishsejm.client.apis

import okhttp3.Call
import okhttp3.HttpUrl
import vote.fetcher.polishsejm.client.infrastructure.ApiClient
import vote.fetcher.polishsejm.client.infrastructure.ApiResponse
import vote.fetcher.polishsejm.client.infrastructure.ClientError
import vote.fetcher.polishsejm.client.infrastructure.ClientException
import vote.fetcher.polishsejm.client.infrastructure.MultiValueMap
import vote.fetcher.polishsejm.client.infrastructure.RequestConfig
import vote.fetcher.polishsejm.client.infrastructure.RequestMethod
import vote.fetcher.polishsejm.client.infrastructure.ResponseType
import vote.fetcher.polishsejm.client.infrastructure.ServerError
import vote.fetcher.polishsejm.client.infrastructure.ServerException
import vote.fetcher.polishsejm.client.infrastructure.Success
import vote.fetcher.polishsejm.client.models.SejmClubDto
import vote.fetcher.polishsejm.client.models.SejmMemberDto
import java.io.IOException

open class ClubsApi(basePath: kotlin.String = defaultBasePath, client: Call.Factory = ApiClient.defaultClient) : ApiClient(
    basePath,
    client,
) {
    companion object {
        @JvmStatic
        val defaultBasePath: String by lazy {
            System.getProperties().getProperty(ApiClient.BASE_URL_KEY, "https://api.sejm.gov.pl")
        }
    }

    /**
     * GET /sejm/term{term}/clubs
     * Returns a list of clubs
     *
     * @param term a Sejm term
     * @return kotlin.collections.List<SejmClubDto>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(
        IllegalStateException::class,
        IOException::class,
        UnsupportedOperationException::class,
        ClientException::class,
        ServerException::class,
    )
    fun sejmTermtermClubsGet(term: kotlin.Int): kotlin.collections.List<SejmClubDto> {
        val localVarResponse = sejmTermtermClubsGetWithHttpInfo(term = term)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as kotlin.collections.List<SejmClubDto>
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException(
                    "Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}",
                    localVarError.statusCode,
                    localVarResponse,
                )
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException(
                    "Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}",
                    localVarError.statusCode,
                    localVarResponse,
                )
            }
        }
    }

    /**
     * GET /sejm/term{term}/clubs
     * Returns a list of clubs
     *
     * @param term a Sejm term
     * @return ApiResponse<kotlin.collections.List<SejmClubDto>?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun sejmTermtermClubsGetWithHttpInfo(term: kotlin.Int): ApiResponse<kotlin.collections.List<SejmClubDto>?> {
        val localVariableConfig = sejmTermtermClubsGetRequestConfig(term = term)

        return request<Unit, kotlin.collections.List<SejmClubDto>>(
            localVariableConfig,
        )
    }

    /**
     * To obtain the request config of the operation sejmTermtermClubsGet
     *
     * @param term a Sejm term
     * @return RequestConfig
     */
    fun sejmTermtermClubsGetRequestConfig(term: kotlin.Int): RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/sejm/term{term}/clubs".replace("{" + "term" + "}", encodeURIComponent(term.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            body = localVariableBody,
        )
    }

    /**
     * GET /sejm/term{term}/clubs/{id}
     * Returns information about a club
     *
     * @param id a club ID
     * @param term a Sejm term
     * @return SejmClubDto
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(
        IllegalStateException::class,
        IOException::class,
        UnsupportedOperationException::class,
        ClientException::class,
        ServerException::class,
    )
    fun sejmTermtermClubsIdGet(
        id: kotlin.String,
        term: kotlin.Int,
    ): SejmClubDto {
        val localVarResponse = sejmTermtermClubsIdGetWithHttpInfo(id = id, term = term)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as SejmClubDto
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException(
                    "Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}",
                    localVarError.statusCode,
                    localVarResponse,
                )
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException(
                    "Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}",
                    localVarError.statusCode,
                    localVarResponse,
                )
            }
        }
    }

    /**
     * GET /sejm/term{term}/clubs/{id}
     * Returns information about a club
     *
     * @param id a club ID
     * @param term a Sejm term
     * @return ApiResponse<SejmClubDto?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun sejmTermtermClubsIdGetWithHttpInfo(
        id: kotlin.String,
        term: kotlin.Int,
    ): ApiResponse<SejmClubDto?> {
        val localVariableConfig = sejmTermtermClubsIdGetRequestConfig(id = id, term = term)

        return request<Unit, SejmClubDto>(
            localVariableConfig,
        )
    }

    /**
     * To obtain the request config of the operation sejmTermtermClubsIdGet
     *
     * @param id a club ID
     * @param term a Sejm term
     * @return RequestConfig
     */
    fun sejmTermtermClubsIdGetRequestConfig(
        id: kotlin.String,
        term: kotlin.Int,
    ): RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/sejm/term{term}/clubs/{id}"
                .replace(
                    "{" + "id" + "}",
                    encodeURIComponent(id.toString()),
                ).replace("{" + "term" + "}", encodeURIComponent(term.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            body = localVariableBody,
        )
    }

    /**
     * GET /sejm/term{term}/clubs/{id}/logo
     * Returns a club image
     *
     * @param id a club id
     * @param term a Sejm term
     * @return kotlin.Any
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(
        IllegalStateException::class,
        IOException::class,
        UnsupportedOperationException::class,
        ClientException::class,
        ServerException::class,
    )
    fun sejmTermtermClubsIdLogoGet(
        id: kotlin.String,
        term: kotlin.Int,
    ): kotlin.Any {
        val localVarResponse = sejmTermtermClubsIdLogoGetWithHttpInfo(id = id, term = term)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as kotlin.Any
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException(
                    "Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}",
                    localVarError.statusCode,
                    localVarResponse,
                )
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException(
                    "Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}",
                    localVarError.statusCode,
                    localVarResponse,
                )
            }
        }
    }

    /**
     * GET /sejm/term{term}/clubs/{id}/logo
     * Returns a club image
     *
     * @param id a club id
     * @param term a Sejm term
     * @return ApiResponse<kotlin.Any?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun sejmTermtermClubsIdLogoGetWithHttpInfo(
        id: kotlin.String,
        term: kotlin.Int,
    ): ApiResponse<kotlin.Any?> {
        val localVariableConfig = sejmTermtermClubsIdLogoGetRequestConfig(id = id, term = term)

        return request<Unit, kotlin.Any>(
            localVariableConfig,
        )
    }

    /**
     * To obtain the request config of the operation sejmTermtermClubsIdLogoGet
     *
     * @param id a club id
     * @param term a Sejm term
     * @return RequestConfig
     */
    fun sejmTermtermClubsIdLogoGetRequestConfig(
        id: kotlin.String,
        term: kotlin.Int,
    ): RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/sejm/term{term}/clubs/{id}/logo"
                .replace(
                    "{" + "id" + "}",
                    encodeURIComponent(id.toString()),
                ).replace("{" + "term" + "}", encodeURIComponent(term.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            body = localVariableBody,
        )
    }

    /**
     * GET /sejm/term{term}/clubs/{id}/members
     * Returns members of this club (current and past)
     *
     * @param id a club ID
     * @param term a Sejm term
     * @return kotlin.collections.List<SejmMemberDto>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(
        IllegalStateException::class,
        IOException::class,
        UnsupportedOperationException::class,
        ClientException::class,
        ServerException::class,
    )
    fun sejmTermtermClubsIdMembersGet(
        id: kotlin.String,
        term: kotlin.Int,
    ): kotlin.collections.List<SejmMemberDto> {
        val localVarResponse = sejmTermtermClubsIdMembersGetWithHttpInfo(id = id, term = term)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as kotlin.collections.List<SejmMemberDto>
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException(
                    "Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}",
                    localVarError.statusCode,
                    localVarResponse,
                )
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException(
                    "Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}",
                    localVarError.statusCode,
                    localVarResponse,
                )
            }
        }
    }

    /**
     * GET /sejm/term{term}/clubs/{id}/members
     * Returns members of this club (current and past)
     *
     * @param id a club ID
     * @param term a Sejm term
     * @return ApiResponse<kotlin.collections.List<SejmMemberDto>?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun sejmTermtermClubsIdMembersGetWithHttpInfo(
        id: kotlin.String,
        term: kotlin.Int,
    ): ApiResponse<kotlin.collections.List<SejmMemberDto>?> {
        val localVariableConfig = sejmTermtermClubsIdMembersGetRequestConfig(id = id, term = term)

        return request<Unit, kotlin.collections.List<SejmMemberDto>>(
            localVariableConfig,
        )
    }

    /**
     * To obtain the request config of the operation sejmTermtermClubsIdMembersGet
     *
     * @param id a club ID
     * @param term a Sejm term
     * @return RequestConfig
     */
    fun sejmTermtermClubsIdMembersGetRequestConfig(
        id: kotlin.String,
        term: kotlin.Int,
    ): RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/sejm/term{term}/clubs/{id}/members"
                .replace(
                    "{" + "id" + "}",
                    encodeURIComponent(id.toString()),
                ).replace("{" + "term" + "}", encodeURIComponent(term.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            body = localVariableBody,
        )
    }

    private fun encodeURIComponent(uriComponent: kotlin.String): kotlin.String =
        HttpUrl
            .Builder()
            .scheme("http")
            .host("localhost")
            .addPathSegment(uriComponent)
            .build()
            .encodedPathSegments[0]
}
