/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused",
)

package vote.fetcher.polishsejm.client.apis

import okhttp3.Call
import okhttp3.HttpUrl
import vote.fetcher.polishsejm.client.infrastructure.ApiClient
import vote.fetcher.polishsejm.client.infrastructure.ApiResponse
import vote.fetcher.polishsejm.client.infrastructure.ClientError
import vote.fetcher.polishsejm.client.infrastructure.ClientException
import vote.fetcher.polishsejm.client.infrastructure.MultiValueMap
import vote.fetcher.polishsejm.client.infrastructure.RequestConfig
import vote.fetcher.polishsejm.client.infrastructure.RequestMethod
import vote.fetcher.polishsejm.client.infrastructure.ResponseType
import vote.fetcher.polishsejm.client.infrastructure.ServerError
import vote.fetcher.polishsejm.client.infrastructure.ServerException
import vote.fetcher.polishsejm.client.infrastructure.Success
import vote.fetcher.polishsejm.client.models.SejmCommitteeDto
import vote.fetcher.polishsejm.client.models.SejmCommitteeSittingDto
import vote.fetcher.polishsejm.client.models.SejmMemberDto
import java.io.IOException

open class CommitteesApi(basePath: kotlin.String = defaultBasePath, client: Call.Factory = ApiClient.defaultClient) : ApiClient(
    basePath,
    client,
) {
    companion object {
        @JvmStatic
        val defaultBasePath: String by lazy {
            System.getProperties().getProperty(ApiClient.BASE_URL_KEY, "https://api.sejm.gov.pl")
        }
    }

    /**
     * GET /sejm/term{term}/committees/{code}
     * Returns a committee details
     *
     * @param code a committee code
     * @param term a Sejm term
     * @return SejmCommitteeDto
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(
        IllegalStateException::class,
        IOException::class,
        UnsupportedOperationException::class,
        ClientException::class,
        ServerException::class,
    )
    fun sejmTermtermCommitteesCodeGet(
        code: kotlin.String,
        term: kotlin.Int,
    ): SejmCommitteeDto {
        val localVarResponse = sejmTermtermCommitteesCodeGetWithHttpInfo(code = code, term = term)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as SejmCommitteeDto
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException(
                    "Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}",
                    localVarError.statusCode,
                    localVarResponse,
                )
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException(
                    "Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}",
                    localVarError.statusCode,
                    localVarResponse,
                )
            }
        }
    }

    /**
     * GET /sejm/term{term}/committees/{code}
     * Returns a committee details
     *
     * @param code a committee code
     * @param term a Sejm term
     * @return ApiResponse<SejmCommitteeDto?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun sejmTermtermCommitteesCodeGetWithHttpInfo(
        code: kotlin.String,
        term: kotlin.Int,
    ): ApiResponse<SejmCommitteeDto?> {
        val localVariableConfig = sejmTermtermCommitteesCodeGetRequestConfig(code = code, term = term)

        return request<Unit, SejmCommitteeDto>(
            localVariableConfig,
        )
    }

    /**
     * To obtain the request config of the operation sejmTermtermCommitteesCodeGet
     *
     * @param code a committee code
     * @param term a Sejm term
     * @return RequestConfig
     */
    fun sejmTermtermCommitteesCodeGetRequestConfig(
        code: kotlin.String,
        term: kotlin.Int,
    ): RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/sejm/term{term}/committees/{code}"
                .replace(
                    "{" + "code" + "}",
                    encodeURIComponent(code.toString()),
                ).replace("{" + "term" + "}", encodeURIComponent(term.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            body = localVariableBody,
        )
    }

    /**
     * GET /sejm/term{term}/committees/{code}/members
     * Returns a list of members (current and past)
     *
     * @param code a committee code
     * @param term a Sejm term
     * @return kotlin.collections.List<SejmMemberDto>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(
        IllegalStateException::class,
        IOException::class,
        UnsupportedOperationException::class,
        ClientException::class,
        ServerException::class,
    )
    fun sejmTermtermCommitteesCodeMembersGet(
        code: kotlin.String,
        term: kotlin.Int,
    ): kotlin.collections.List<SejmMemberDto> {
        val localVarResponse = sejmTermtermCommitteesCodeMembersGetWithHttpInfo(code = code, term = term)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as kotlin.collections.List<SejmMemberDto>
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException(
                    "Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}",
                    localVarError.statusCode,
                    localVarResponse,
                )
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException(
                    "Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}",
                    localVarError.statusCode,
                    localVarResponse,
                )
            }
        }
    }

    /**
     * GET /sejm/term{term}/committees/{code}/members
     * Returns a list of members (current and past)
     *
     * @param code a committee code
     * @param term a Sejm term
     * @return ApiResponse<kotlin.collections.List<SejmMemberDto>?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun sejmTermtermCommitteesCodeMembersGetWithHttpInfo(
        code: kotlin.String,
        term: kotlin.Int,
    ): ApiResponse<kotlin.collections.List<SejmMemberDto>?> {
        val localVariableConfig = sejmTermtermCommitteesCodeMembersGetRequestConfig(code = code, term = term)

        return request<Unit, kotlin.collections.List<SejmMemberDto>>(
            localVariableConfig,
        )
    }

    /**
     * To obtain the request config of the operation sejmTermtermCommitteesCodeMembersGet
     *
     * @param code a committee code
     * @param term a Sejm term
     * @return RequestConfig
     */
    fun sejmTermtermCommitteesCodeMembersGetRequestConfig(
        code: kotlin.String,
        term: kotlin.Int,
    ): RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/sejm/term{term}/committees/{code}/members".replace("{" + "code" + "}", encodeURIComponent(code.toString())).replace(
                "{" + "term" + "}",
                encodeURIComponent(term.toString()),
            ),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            body = localVariableBody,
        )
    }

    /**
     * GET /sejm/term{term}/committees/{code}/sittings
     * Returns a list of sittings
     *
     * @param code a committee code
     * @param term a Sejm term
     * @param cancelled also include cancelled sittings (optional)
     * @return kotlin.collections.List<SejmCommitteeSittingDto>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(
        IllegalStateException::class,
        IOException::class,
        UnsupportedOperationException::class,
        ClientException::class,
        ServerException::class,
    )
    fun sejmTermtermCommitteesCodeSittingsGet(
        code: kotlin.String,
        term: kotlin.Int,
        cancelled: kotlin.Boolean? = null,
    ): kotlin.collections.List<SejmCommitteeSittingDto> {
        val localVarResponse = sejmTermtermCommitteesCodeSittingsGetWithHttpInfo(code = code, term = term, cancelled = cancelled)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as kotlin.collections.List<SejmCommitteeSittingDto>
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException(
                    "Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}",
                    localVarError.statusCode,
                    localVarResponse,
                )
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException(
                    "Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}",
                    localVarError.statusCode,
                    localVarResponse,
                )
            }
        }
    }

    /**
     * GET /sejm/term{term}/committees/{code}/sittings
     * Returns a list of sittings
     *
     * @param code a committee code
     * @param term a Sejm term
     * @param cancelled also include cancelled sittings (optional)
     * @return ApiResponse<kotlin.collections.List<SejmCommitteeSittingDto>?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun sejmTermtermCommitteesCodeSittingsGetWithHttpInfo(
        code: kotlin.String,
        term: kotlin.Int,
        cancelled: kotlin.Boolean?,
    ): ApiResponse<kotlin.collections.List<SejmCommitteeSittingDto>?> {
        val localVariableConfig = sejmTermtermCommitteesCodeSittingsGetRequestConfig(code = code, term = term, cancelled = cancelled)

        return request<Unit, kotlin.collections.List<SejmCommitteeSittingDto>>(
            localVariableConfig,
        )
    }

    /**
     * To obtain the request config of the operation sejmTermtermCommitteesCodeSittingsGet
     *
     * @param code a committee code
     * @param term a Sejm term
     * @param cancelled also include cancelled sittings (optional)
     * @return RequestConfig
     */
    fun sejmTermtermCommitteesCodeSittingsGetRequestConfig(
        code: kotlin.String,
        term: kotlin.Int,
        cancelled: kotlin.Boolean?,
    ): RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
            .apply {
                if (cancelled != null) {
                    put("cancelled", listOf(cancelled.toString()))
                }
            }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/sejm/term{term}/committees/{code}/sittings".replace("{" + "code" + "}", encodeURIComponent(code.toString())).replace(
                "{" + "term" + "}",
                encodeURIComponent(term.toString()),
            ),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            body = localVariableBody,
        )
    }

    /**
     * GET /sejm/term{term}/committees/{code}/sittings/{num}
     * Returns details about a sitting
     *
     * @param code a committee code
     * @param num a sitting number
     * @param term a Sejm term
     * @return SejmCommitteeSittingDto
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(
        IllegalStateException::class,
        IOException::class,
        UnsupportedOperationException::class,
        ClientException::class,
        ServerException::class,
    )
    fun sejmTermtermCommitteesCodeSittingsNumGet(
        code: kotlin.String,
        num: kotlin.Int,
        term: kotlin.Int,
    ): SejmCommitteeSittingDto {
        val localVarResponse = sejmTermtermCommitteesCodeSittingsNumGetWithHttpInfo(code = code, num = num, term = term)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as SejmCommitteeSittingDto
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException(
                    "Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}",
                    localVarError.statusCode,
                    localVarResponse,
                )
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException(
                    "Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}",
                    localVarError.statusCode,
                    localVarResponse,
                )
            }
        }
    }

    /**
     * GET /sejm/term{term}/committees/{code}/sittings/{num}
     * Returns details about a sitting
     *
     * @param code a committee code
     * @param num a sitting number
     * @param term a Sejm term
     * @return ApiResponse<SejmCommitteeSittingDto?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun sejmTermtermCommitteesCodeSittingsNumGetWithHttpInfo(
        code: kotlin.String,
        num: kotlin.Int,
        term: kotlin.Int,
    ): ApiResponse<SejmCommitteeSittingDto?> {
        val localVariableConfig = sejmTermtermCommitteesCodeSittingsNumGetRequestConfig(code = code, num = num, term = term)

        return request<Unit, SejmCommitteeSittingDto>(
            localVariableConfig,
        )
    }

    /**
     * To obtain the request config of the operation sejmTermtermCommitteesCodeSittingsNumGet
     *
     * @param code a committee code
     * @param num a sitting number
     * @param term a Sejm term
     * @return RequestConfig
     */
    fun sejmTermtermCommitteesCodeSittingsNumGetRequestConfig(
        code: kotlin.String,
        num: kotlin.Int,
        term: kotlin.Int,
    ): RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/sejm/term{term}/committees/{code}/sittings/{num}"
                .replace(
                    "{" + "code" + "}",
                    encodeURIComponent(code.toString()),
                ).replace(
                    "{" + "num" + "}",
                    encodeURIComponent(num.toString()),
                ).replace("{" + "term" + "}", encodeURIComponent(term.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            body = localVariableBody,
        )
    }

    /**
     * GET /sejm/term{term}/committees/{code}/sittings/{num}/html
     * Returns transcript of the meeting in the HTML format
     *
     * @param code a committee code
     * @param num a sitting number
     * @param term a Sejm term
     * @return kotlin.String
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(
        IllegalStateException::class,
        IOException::class,
        UnsupportedOperationException::class,
        ClientException::class,
        ServerException::class,
    )
    fun sejmTermtermCommitteesCodeSittingsNumHtmlGet(
        code: kotlin.String,
        num: kotlin.Int,
        term: kotlin.Int,
    ): kotlin.String {
        val localVarResponse = sejmTermtermCommitteesCodeSittingsNumHtmlGetWithHttpInfo(code = code, num = num, term = term)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as kotlin.String
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException(
                    "Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}",
                    localVarError.statusCode,
                    localVarResponse,
                )
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException(
                    "Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}",
                    localVarError.statusCode,
                    localVarResponse,
                )
            }
        }
    }

    /**
     * GET /sejm/term{term}/committees/{code}/sittings/{num}/html
     * Returns transcript of the meeting in the HTML format
     *
     * @param code a committee code
     * @param num a sitting number
     * @param term a Sejm term
     * @return ApiResponse<kotlin.String?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun sejmTermtermCommitteesCodeSittingsNumHtmlGetWithHttpInfo(
        code: kotlin.String,
        num: kotlin.Int,
        term: kotlin.Int,
    ): ApiResponse<kotlin.String?> {
        val localVariableConfig = sejmTermtermCommitteesCodeSittingsNumHtmlGetRequestConfig(code = code, num = num, term = term)

        return request<Unit, kotlin.String>(
            localVariableConfig,
        )
    }

    /**
     * To obtain the request config of the operation sejmTermtermCommitteesCodeSittingsNumHtmlGet
     *
     * @param code a committee code
     * @param num a sitting number
     * @param term a Sejm term
     * @return RequestConfig
     */
    fun sejmTermtermCommitteesCodeSittingsNumHtmlGetRequestConfig(
        code: kotlin.String,
        num: kotlin.Int,
        term: kotlin.Int,
    ): RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/sejm/term{term}/committees/{code}/sittings/{num}/html"
                .replace(
                    "{" + "code" + "}",
                    encodeURIComponent(code.toString()),
                ).replace(
                    "{" + "num" + "}",
                    encodeURIComponent(num.toString()),
                ).replace("{" + "term" + "}", encodeURIComponent(term.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            body = localVariableBody,
        )
    }

    /**
     * GET /sejm/term{term}/committees/{code}/sittings/{num}/pdf
     * Returns transcript of the meeting in the PDF format
     *
     * @param code a committee code
     * @param num a sitting number
     * @param term a Sejm term
     * @return void
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Throws(
        IllegalStateException::class,
        IOException::class,
        UnsupportedOperationException::class,
        ClientException::class,
        ServerException::class,
    )
    fun sejmTermtermCommitteesCodeSittingsNumPdfGet(
        code: kotlin.String,
        num: kotlin.Int,
        term: kotlin.Int,
    ) {
        val localVarResponse = sejmTermtermCommitteesCodeSittingsNumPdfGetWithHttpInfo(code = code, num = num, term = term)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> Unit
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException(
                    "Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}",
                    localVarError.statusCode,
                    localVarResponse,
                )
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException(
                    "Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}",
                    localVarError.statusCode,
                    localVarResponse,
                )
            }
        }
    }

    /**
     * GET /sejm/term{term}/committees/{code}/sittings/{num}/pdf
     * Returns transcript of the meeting in the PDF format
     *
     * @param code a committee code
     * @param num a sitting number
     * @param term a Sejm term
     * @return ApiResponse<Unit?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Throws(IllegalStateException::class, IOException::class)
    fun sejmTermtermCommitteesCodeSittingsNumPdfGetWithHttpInfo(
        code: kotlin.String,
        num: kotlin.Int,
        term: kotlin.Int,
    ): ApiResponse<Unit?> {
        val localVariableConfig = sejmTermtermCommitteesCodeSittingsNumPdfGetRequestConfig(code = code, num = num, term = term)

        return request<Unit, Unit>(
            localVariableConfig,
        )
    }

    /**
     * To obtain the request config of the operation sejmTermtermCommitteesCodeSittingsNumPdfGet
     *
     * @param code a committee code
     * @param num a sitting number
     * @param term a Sejm term
     * @return RequestConfig
     */
    fun sejmTermtermCommitteesCodeSittingsNumPdfGetRequestConfig(
        code: kotlin.String,
        num: kotlin.Int,
        term: kotlin.Int,
    ): RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/sejm/term{term}/committees/{code}/sittings/{num}/pdf"
                .replace(
                    "{" + "code" + "}",
                    encodeURIComponent(code.toString()),
                ).replace(
                    "{" + "num" + "}",
                    encodeURIComponent(num.toString()),
                ).replace("{" + "term" + "}", encodeURIComponent(term.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            body = localVariableBody,
        )
    }

    /**
     * GET /sejm/term{term}/committees
     * Returns a list of committees
     *
     * @param term a Sejm term
     * @return kotlin.collections.List<SejmCommitteeDto>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(
        IllegalStateException::class,
        IOException::class,
        UnsupportedOperationException::class,
        ClientException::class,
        ServerException::class,
    )
    fun sejmTermtermCommitteesGet(term: kotlin.Int): kotlin.collections.List<SejmCommitteeDto> {
        val localVarResponse = sejmTermtermCommitteesGetWithHttpInfo(term = term)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as kotlin.collections.List<SejmCommitteeDto>
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException(
                    "Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}",
                    localVarError.statusCode,
                    localVarResponse,
                )
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException(
                    "Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}",
                    localVarError.statusCode,
                    localVarResponse,
                )
            }
        }
    }

    /**
     * GET /sejm/term{term}/committees
     * Returns a list of committees
     *
     * @param term a Sejm term
     * @return ApiResponse<kotlin.collections.List<SejmCommitteeDto>?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun sejmTermtermCommitteesGetWithHttpInfo(term: kotlin.Int): ApiResponse<kotlin.collections.List<SejmCommitteeDto>?> {
        val localVariableConfig = sejmTermtermCommitteesGetRequestConfig(term = term)

        return request<Unit, kotlin.collections.List<SejmCommitteeDto>>(
            localVariableConfig,
        )
    }

    /**
     * To obtain the request config of the operation sejmTermtermCommitteesGet
     *
     * @param term a Sejm term
     * @return RequestConfig
     */
    fun sejmTermtermCommitteesGetRequestConfig(term: kotlin.Int): RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/sejm/term{term}/committees".replace("{" + "term" + "}", encodeURIComponent(term.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            body = localVariableBody,
        )
    }

    /**
     * GET /sejm/term{term}/committees/sittings/{date}
     * Returns a list of sittings for a given date
     *
     * @param date a date
     * @param term a Sejm term
     * @param cancelled also include cancelled sittings (optional)
     * @return kotlin.collections.List<SejmCommitteeSittingDto>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(
        IllegalStateException::class,
        IOException::class,
        UnsupportedOperationException::class,
        ClientException::class,
        ServerException::class,
    )
    fun sejmTermtermCommitteesSittingsDateGet(
        date: java.time.LocalDate,
        term: kotlin.Int,
        cancelled: kotlin.Boolean? = null,
    ): kotlin.collections.List<SejmCommitteeSittingDto> {
        val localVarResponse = sejmTermtermCommitteesSittingsDateGetWithHttpInfo(date = date, term = term, cancelled = cancelled)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as kotlin.collections.List<SejmCommitteeSittingDto>
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException(
                    "Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}",
                    localVarError.statusCode,
                    localVarResponse,
                )
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException(
                    "Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}",
                    localVarError.statusCode,
                    localVarResponse,
                )
            }
        }
    }

    /**
     * GET /sejm/term{term}/committees/sittings/{date}
     * Returns a list of sittings for a given date
     *
     * @param date a date
     * @param term a Sejm term
     * @param cancelled also include cancelled sittings (optional)
     * @return ApiResponse<kotlin.collections.List<SejmCommitteeSittingDto>?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun sejmTermtermCommitteesSittingsDateGetWithHttpInfo(
        date: java.time.LocalDate,
        term: kotlin.Int,
        cancelled: kotlin.Boolean?,
    ): ApiResponse<kotlin.collections.List<SejmCommitteeSittingDto>?> {
        val localVariableConfig = sejmTermtermCommitteesSittingsDateGetRequestConfig(date = date, term = term, cancelled = cancelled)

        return request<Unit, kotlin.collections.List<SejmCommitteeSittingDto>>(
            localVariableConfig,
        )
    }

    /**
     * To obtain the request config of the operation sejmTermtermCommitteesSittingsDateGet
     *
     * @param date a date
     * @param term a Sejm term
     * @param cancelled also include cancelled sittings (optional)
     * @return RequestConfig
     */
    fun sejmTermtermCommitteesSittingsDateGetRequestConfig(
        date: java.time.LocalDate,
        term: kotlin.Int,
        cancelled: kotlin.Boolean?,
    ): RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
            .apply {
                if (cancelled != null) {
                    put("cancelled", listOf(cancelled.toString()))
                }
            }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/sejm/term{term}/committees/sittings/{date}".replace("{" + "date" + "}", encodeURIComponent(date.toString())).replace(
                "{" + "term" + "}",
                encodeURIComponent(term.toString()),
            ),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            body = localVariableBody,
        )
    }

    private fun encodeURIComponent(uriComponent: kotlin.String): kotlin.String =
        HttpUrl
            .Builder()
            .scheme("http")
            .host("localhost")
            .addPathSegment(uriComponent)
            .build()
            .encodedPathSegments[0]
}
