/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused",
)

package vote.fetcher.polishsejm.client.apis

import okhttp3.Call
import okhttp3.HttpUrl
import vote.fetcher.polishsejm.client.infrastructure.ApiClient
import vote.fetcher.polishsejm.client.infrastructure.ApiResponse
import vote.fetcher.polishsejm.client.infrastructure.ClientError
import vote.fetcher.polishsejm.client.infrastructure.ClientException
import vote.fetcher.polishsejm.client.infrastructure.MultiValueMap
import vote.fetcher.polishsejm.client.infrastructure.RequestConfig
import vote.fetcher.polishsejm.client.infrastructure.RequestMethod
import vote.fetcher.polishsejm.client.infrastructure.ResponseType
import vote.fetcher.polishsejm.client.infrastructure.ServerError
import vote.fetcher.polishsejm.client.infrastructure.ServerException
import vote.fetcher.polishsejm.client.infrastructure.Success
import vote.fetcher.polishsejm.client.models.SejmMPDto
import vote.fetcher.polishsejm.client.models.SejmVoteMPDto
import vote.fetcher.polishsejm.client.models.SejmVotingStatDto
import java.io.IOException

open class MPApi(basePath: kotlin.String = defaultBasePath, client: Call.Factory = ApiClient.defaultClient) : ApiClient(basePath, client) {
    companion object {
        @JvmStatic
        val defaultBasePath: String by lazy {
            System.getProperties().getProperty(ApiClient.BASE_URL_KEY, "https://api.sejm.gov.pl")
        }
    }

    /**
     * GET /sejm/term{term}/MP
     * Returns a list of MPs
     *
     * @param term a Sejm term
     * @return kotlin.collections.List<SejmMPDto>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(
        IllegalStateException::class,
        IOException::class,
        UnsupportedOperationException::class,
        ClientException::class,
        ServerException::class,
    )
    fun sejmTermtermMPGet(term: kotlin.Int): kotlin.collections.List<SejmMPDto> {
        val localVarResponse = sejmTermtermMPGetWithHttpInfo(term = term)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as kotlin.collections.List<SejmMPDto>
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException(
                    "Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}",
                    localVarError.statusCode,
                    localVarResponse,
                )
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException(
                    "Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}",
                    localVarError.statusCode,
                    localVarResponse,
                )
            }
        }
    }

    /**
     * GET /sejm/term{term}/MP
     * Returns a list of MPs
     *
     * @param term a Sejm term
     * @return ApiResponse<kotlin.collections.List<SejmMPDto>?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun sejmTermtermMPGetWithHttpInfo(term: kotlin.Int): ApiResponse<kotlin.collections.List<SejmMPDto>?> {
        val localVariableConfig = sejmTermtermMPGetRequestConfig(term = term)

        return request<Unit, kotlin.collections.List<SejmMPDto>>(
            localVariableConfig,
        )
    }

    /**
     * To obtain the request config of the operation sejmTermtermMPGet
     *
     * @param term a Sejm term
     * @return RequestConfig
     */
    fun sejmTermtermMPGetRequestConfig(term: kotlin.Int): RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/sejm/term{term}/MP".replace("{" + "term" + "}", encodeURIComponent(term.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            body = localVariableBody,
        )
    }

    /**
     * GET /sejm/term{term}/MP/{id}
     * Returns an information about an MP
     *
     * @param id an MP ID
     * @param term a Sejm term
     * @return SejmMPDto
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(
        IllegalStateException::class,
        IOException::class,
        UnsupportedOperationException::class,
        ClientException::class,
        ServerException::class,
    )
    fun sejmTermtermMPIdGet(
        id: kotlin.Int,
        term: kotlin.Int,
    ): SejmMPDto {
        val localVarResponse = sejmTermtermMPIdGetWithHttpInfo(id = id, term = term)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as SejmMPDto
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException(
                    "Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}",
                    localVarError.statusCode,
                    localVarResponse,
                )
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException(
                    "Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}",
                    localVarError.statusCode,
                    localVarResponse,
                )
            }
        }
    }

    /**
     * GET /sejm/term{term}/MP/{id}
     * Returns an information about an MP
     *
     * @param id an MP ID
     * @param term a Sejm term
     * @return ApiResponse<SejmMPDto?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun sejmTermtermMPIdGetWithHttpInfo(
        id: kotlin.Int,
        term: kotlin.Int,
    ): ApiResponse<SejmMPDto?> {
        val localVariableConfig = sejmTermtermMPIdGetRequestConfig(id = id, term = term)

        return request<Unit, SejmMPDto>(
            localVariableConfig,
        )
    }

    /**
     * To obtain the request config of the operation sejmTermtermMPIdGet
     *
     * @param id an MP ID
     * @param term a Sejm term
     * @return RequestConfig
     */
    fun sejmTermtermMPIdGetRequestConfig(
        id: kotlin.Int,
        term: kotlin.Int,
    ): RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/sejm/term{term}/MP/{id}"
                .replace(
                    "{" + "id" + "}",
                    encodeURIComponent(id.toString()),
                ).replace("{" + "term" + "}", encodeURIComponent(term.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            body = localVariableBody,
        )
    }

    /**
     * GET /sejm/term{term}/MP/{id}/photo
     * Returns an MP photo
     *
     * @param id an MP ID
     * @param term a Sejm term
     * @return void
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Throws(
        IllegalStateException::class,
        IOException::class,
        UnsupportedOperationException::class,
        ClientException::class,
        ServerException::class,
    )
    fun sejmTermtermMPIdPhotoGet(
        id: kotlin.Int,
        term: kotlin.Int,
    ) {
        val localVarResponse = sejmTermtermMPIdPhotoGetWithHttpInfo(id = id, term = term)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> Unit
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException(
                    "Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}",
                    localVarError.statusCode,
                    localVarResponse,
                )
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException(
                    "Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}",
                    localVarError.statusCode,
                    localVarResponse,
                )
            }
        }
    }

    /**
     * GET /sejm/term{term}/MP/{id}/photo
     * Returns an MP photo
     *
     * @param id an MP ID
     * @param term a Sejm term
     * @return ApiResponse<Unit?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Throws(IllegalStateException::class, IOException::class)
    fun sejmTermtermMPIdPhotoGetWithHttpInfo(
        id: kotlin.Int,
        term: kotlin.Int,
    ): ApiResponse<Unit?> {
        val localVariableConfig = sejmTermtermMPIdPhotoGetRequestConfig(id = id, term = term)

        return request<Unit, Unit>(
            localVariableConfig,
        )
    }

    /**
     * To obtain the request config of the operation sejmTermtermMPIdPhotoGet
     *
     * @param id an MP ID
     * @param term a Sejm term
     * @return RequestConfig
     */
    fun sejmTermtermMPIdPhotoGetRequestConfig(
        id: kotlin.Int,
        term: kotlin.Int,
    ): RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/sejm/term{term}/MP/{id}/photo"
                .replace(
                    "{" + "id" + "}",
                    encodeURIComponent(id.toString()),
                ).replace("{" + "term" + "}", encodeURIComponent(term.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            body = localVariableBody,
        )
    }

    /**
     * GET /sejm/term{term}/MP/{id}/photo-mini
     * Returns an MP photo in small size
     *
     * @param id an MP ID
     * @param term a Sejm term
     * @return void
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Throws(
        IllegalStateException::class,
        IOException::class,
        UnsupportedOperationException::class,
        ClientException::class,
        ServerException::class,
    )
    fun sejmTermtermMPIdPhotoMiniGet(
        id: kotlin.Int,
        term: kotlin.Int,
    ) {
        val localVarResponse = sejmTermtermMPIdPhotoMiniGetWithHttpInfo(id = id, term = term)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> Unit
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException(
                    "Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}",
                    localVarError.statusCode,
                    localVarResponse,
                )
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException(
                    "Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}",
                    localVarError.statusCode,
                    localVarResponse,
                )
            }
        }
    }

    /**
     * GET /sejm/term{term}/MP/{id}/photo-mini
     * Returns an MP photo in small size
     *
     * @param id an MP ID
     * @param term a Sejm term
     * @return ApiResponse<Unit?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Throws(IllegalStateException::class, IOException::class)
    fun sejmTermtermMPIdPhotoMiniGetWithHttpInfo(
        id: kotlin.Int,
        term: kotlin.Int,
    ): ApiResponse<Unit?> {
        val localVariableConfig = sejmTermtermMPIdPhotoMiniGetRequestConfig(id = id, term = term)

        return request<Unit, Unit>(
            localVariableConfig,
        )
    }

    /**
     * To obtain the request config of the operation sejmTermtermMPIdPhotoMiniGet
     *
     * @param id an MP ID
     * @param term a Sejm term
     * @return RequestConfig
     */
    fun sejmTermtermMPIdPhotoMiniGetRequestConfig(
        id: kotlin.Int,
        term: kotlin.Int,
    ): RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/sejm/term{term}/MP/{id}/photo-mini"
                .replace(
                    "{" + "id" + "}",
                    encodeURIComponent(id.toString()),
                ).replace("{" + "term" + "}", encodeURIComponent(term.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            body = localVariableBody,
        )
    }

    /**
     * GET /sejm/term{term}/MP/{id}/votings/{sitting}/{date}
     * Returns an information about votings for an MP
     *
     * @param date a date
     * @param id an MP ID
     * @param sitting a sitting number
     * @param term a Sejm term
     * @return kotlin.collections.List<SejmVoteMPDto>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(
        IllegalStateException::class,
        IOException::class,
        UnsupportedOperationException::class,
        ClientException::class,
        ServerException::class,
    )
    fun sejmTermtermMPIdVotingsSittingDateGet(
        date: java.time.LocalDate,
        id: kotlin.Int,
        sitting: kotlin.Int,
        term: kotlin.Int,
    ): kotlin.collections.List<SejmVoteMPDto> {
        val localVarResponse = sejmTermtermMPIdVotingsSittingDateGetWithHttpInfo(date = date, id = id, sitting = sitting, term = term)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as kotlin.collections.List<SejmVoteMPDto>
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException(
                    "Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}",
                    localVarError.statusCode,
                    localVarResponse,
                )
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException(
                    "Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}",
                    localVarError.statusCode,
                    localVarResponse,
                )
            }
        }
    }

    /**
     * GET /sejm/term{term}/MP/{id}/votings/{sitting}/{date}
     * Returns an information about votings for an MP
     *
     * @param date a date
     * @param id an MP ID
     * @param sitting a sitting number
     * @param term a Sejm term
     * @return ApiResponse<kotlin.collections.List<SejmVoteMPDto>?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun sejmTermtermMPIdVotingsSittingDateGetWithHttpInfo(
        date: java.time.LocalDate,
        id: kotlin.Int,
        sitting: kotlin.Int,
        term: kotlin.Int,
    ): ApiResponse<kotlin.collections.List<SejmVoteMPDto>?> {
        val localVariableConfig = sejmTermtermMPIdVotingsSittingDateGetRequestConfig(date = date, id = id, sitting = sitting, term = term)

        return request<Unit, kotlin.collections.List<SejmVoteMPDto>>(
            localVariableConfig,
        )
    }

    /**
     * To obtain the request config of the operation sejmTermtermMPIdVotingsSittingDateGet
     *
     * @param date a date
     * @param id an MP ID
     * @param sitting a sitting number
     * @param term a Sejm term
     * @return RequestConfig
     */
    fun sejmTermtermMPIdVotingsSittingDateGetRequestConfig(
        date: java.time.LocalDate,
        id: kotlin.Int,
        sitting: kotlin.Int,
        term: kotlin.Int,
    ): RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/sejm/term{term}/MP/{id}/votings/{sitting}/{date}"
                .replace(
                    "{" + "date" + "}",
                    encodeURIComponent(date.toString()),
                ).replace(
                    "{" + "id" + "}",
                    encodeURIComponent(id.toString()),
                ).replace("{" + "sitting" + "}", encodeURIComponent(sitting.toString()))
                .replace(
                    "{" + "term" + "}",
                    encodeURIComponent(term.toString()),
                ),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            body = localVariableBody,
        )
    }

    /**
     * GET /sejm/term{term}/MP/{id}/votings/stats
     * Returns statistics about votings for an MP
     *
     * @param id an MP ID
     * @param term a Sejm term
     * @return kotlin.collections.List<SejmVotingStatDto>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(
        IllegalStateException::class,
        IOException::class,
        UnsupportedOperationException::class,
        ClientException::class,
        ServerException::class,
    )
    fun sejmTermtermMPIdVotingsStatsGet(
        id: kotlin.Int,
        term: kotlin.Int,
    ): kotlin.collections.List<SejmVotingStatDto> {
        val localVarResponse = sejmTermtermMPIdVotingsStatsGetWithHttpInfo(id = id, term = term)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as kotlin.collections.List<SejmVotingStatDto>
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException(
                    "Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}",
                    localVarError.statusCode,
                    localVarResponse,
                )
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException(
                    "Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}",
                    localVarError.statusCode,
                    localVarResponse,
                )
            }
        }
    }

    /**
     * GET /sejm/term{term}/MP/{id}/votings/stats
     * Returns statistics about votings for an MP
     *
     * @param id an MP ID
     * @param term a Sejm term
     * @return ApiResponse<kotlin.collections.List<SejmVotingStatDto>?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun sejmTermtermMPIdVotingsStatsGetWithHttpInfo(
        id: kotlin.Int,
        term: kotlin.Int,
    ): ApiResponse<kotlin.collections.List<SejmVotingStatDto>?> {
        val localVariableConfig = sejmTermtermMPIdVotingsStatsGetRequestConfig(id = id, term = term)

        return request<Unit, kotlin.collections.List<SejmVotingStatDto>>(
            localVariableConfig,
        )
    }

    /**
     * To obtain the request config of the operation sejmTermtermMPIdVotingsStatsGet
     *
     * @param id an MP ID
     * @param term a Sejm term
     * @return RequestConfig
     */
    fun sejmTermtermMPIdVotingsStatsGetRequestConfig(
        id: kotlin.Int,
        term: kotlin.Int,
    ): RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/sejm/term{term}/MP/{id}/votings/stats"
                .replace(
                    "{" + "id" + "}",
                    encodeURIComponent(id.toString()),
                ).replace("{" + "term" + "}", encodeURIComponent(term.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            body = localVariableBody,
        )
    }

    private fun encodeURIComponent(uriComponent: kotlin.String): kotlin.String =
        HttpUrl
            .Builder()
            .scheme("http")
            .host("localhost")
            .addPathSegment(uriComponent)
            .build()
            .encodedPathSegments[0]
}
