/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused",
)

package vote.fetcher.polishsejm.client.apis

import okhttp3.Call
import okhttp3.HttpUrl
import vote.fetcher.polishsejm.client.infrastructure.ApiClient
import vote.fetcher.polishsejm.client.infrastructure.ApiResponse
import vote.fetcher.polishsejm.client.infrastructure.ClientError
import vote.fetcher.polishsejm.client.infrastructure.ClientException
import vote.fetcher.polishsejm.client.infrastructure.MultiValueMap
import vote.fetcher.polishsejm.client.infrastructure.RequestConfig
import vote.fetcher.polishsejm.client.infrastructure.RequestMethod
import vote.fetcher.polishsejm.client.infrastructure.ResponseType
import vote.fetcher.polishsejm.client.infrastructure.ServerError
import vote.fetcher.polishsejm.client.infrastructure.ServerException
import vote.fetcher.polishsejm.client.infrastructure.Success
import vote.fetcher.polishsejm.client.models.SejmProcessDetailsDto
import vote.fetcher.polishsejm.client.models.SejmProcessHeaderDto
import java.io.IOException

open class ProcessesApi(basePath: kotlin.String = defaultBasePath, client: Call.Factory = ApiClient.defaultClient) : ApiClient(
    basePath,
    client,
) {
    companion object {
        @JvmStatic
        val defaultBasePath: String by lazy {
            System.getProperties().getProperty(ApiClient.BASE_URL_KEY, "https://api.sejm.gov.pl")
        }
    }

    /**
     * GET /sejm/term{term}/processes
     * Returns a list of legislative processes
     *
     * @param term a Sejm term
     * @param documentType a type of a document (optional)
     * @param limit controls the maximum number of items that may be returned for a single request (optional, default to 50)
     * @param modifiedSince filters processes  modified since specified date (optional)
     * @param offset controls the starting point within the collection of resource results (optional, default to 0)
     * @param passed only passed acts (optional)
     * @param sort sorts objects by specified field, to sort in descending order add a minus sign before field name (optional)
     * @param sortBy sorts objects by specified field, to sort in descending order add a minus sign before field name (optional)
     * @param title filters processes containing a specified string in a title (optional)
     * @return kotlin.collections.List<SejmProcessHeaderDto>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(
        IllegalStateException::class,
        IOException::class,
        UnsupportedOperationException::class,
        ClientException::class,
        ServerException::class,
    )
    fun sejmTermtermProcessesGet(
        term: kotlin.Int,
        documentType: kotlin.String? = null,
        limit: kotlin.Int? = 50,
        modifiedSince: java.time.LocalDateTime? = null,
        offset: kotlin.Int? = 0,
        passed: kotlin.Boolean? = null,
        sort: kotlin.String? = null,
        sortBy: kotlin.String? = null,
        title: kotlin.String? = null,
    ): kotlin.collections.List<SejmProcessHeaderDto> {
        val localVarResponse =
            sejmTermtermProcessesGetWithHttpInfo(
                term = term,
                documentType = documentType,
                limit = limit,
                modifiedSince = modifiedSince,
                offset = offset,
                passed = passed,
                sort = sort,
                sortBy = sortBy,
                title = title,
            )

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as kotlin.collections.List<SejmProcessHeaderDto>
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException(
                    "Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}",
                    localVarError.statusCode,
                    localVarResponse,
                )
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException(
                    "Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}",
                    localVarError.statusCode,
                    localVarResponse,
                )
            }
        }
    }

    /**
     * GET /sejm/term{term}/processes
     * Returns a list of legislative processes
     *
     * @param term a Sejm term
     * @param documentType a type of a document (optional)
     * @param limit controls the maximum number of items that may be returned for a single request (optional, default to 50)
     * @param modifiedSince filters processes  modified since specified date (optional)
     * @param offset controls the starting point within the collection of resource results (optional, default to 0)
     * @param passed only passed acts (optional)
     * @param sort sorts objects by specified field, to sort in descending order add a minus sign before field name (optional)
     * @param sortBy sorts objects by specified field, to sort in descending order add a minus sign before field name (optional)
     * @param title filters processes containing a specified string in a title (optional)
     * @return ApiResponse<kotlin.collections.List<SejmProcessHeaderDto>?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun sejmTermtermProcessesGetWithHttpInfo(
        term: kotlin.Int,
        documentType: kotlin.String?,
        limit: kotlin.Int?,
        modifiedSince: java.time.LocalDateTime?,
        offset: kotlin.Int?,
        passed: kotlin.Boolean?,
        sort: kotlin.String?,
        sortBy: kotlin.String?,
        title: kotlin.String?,
    ): ApiResponse<kotlin.collections.List<SejmProcessHeaderDto>?> {
        val localVariableConfig =
            sejmTermtermProcessesGetRequestConfig(
                term = term,
                documentType = documentType,
                limit = limit,
                modifiedSince = modifiedSince,
                offset = offset,
                passed = passed,
                sort = sort,
                sortBy = sortBy,
                title = title,
            )

        return request<Unit, kotlin.collections.List<SejmProcessHeaderDto>>(
            localVariableConfig,
        )
    }

    /**
     * To obtain the request config of the operation sejmTermtermProcessesGet
     *
     * @param term a Sejm term
     * @param documentType a type of a document (optional)
     * @param limit controls the maximum number of items that may be returned for a single request (optional, default to 50)
     * @param modifiedSince filters processes  modified since specified date (optional)
     * @param offset controls the starting point within the collection of resource results (optional, default to 0)
     * @param passed only passed acts (optional)
     * @param sort sorts objects by specified field, to sort in descending order add a minus sign before field name (optional)
     * @param sortBy sorts objects by specified field, to sort in descending order add a minus sign before field name (optional)
     * @param title filters processes containing a specified string in a title (optional)
     * @return RequestConfig
     */
    fun sejmTermtermProcessesGetRequestConfig(
        term: kotlin.Int,
        documentType: kotlin.String?,
        limit: kotlin.Int?,
        modifiedSince: java.time.LocalDateTime?,
        offset: kotlin.Int?,
        passed: kotlin.Boolean?,
        sort: kotlin.String?,
        sortBy: kotlin.String?,
        title: kotlin.String?,
    ): RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
            .apply {
                if (documentType != null) {
                    put("documentType", listOf(documentType.toString()))
                }
                if (limit != null) {
                    put("limit", listOf(limit.toString()))
                }
                if (modifiedSince != null) {
                    put("modifiedSince", listOf(parseDateToQueryString<java.time.LocalDateTime>(modifiedSince)))
                }
                if (offset != null) {
                    put("offset", listOf(offset.toString()))
                }
                if (passed != null) {
                    put("passed", listOf(passed.toString()))
                }
                if (sort != null) {
                    put("sort", listOf(sort.toString()))
                }
                if (sortBy != null) {
                    put("sort_by", listOf(sortBy.toString()))
                }
                if (title != null) {
                    put("title", listOf(title.toString()))
                }
            }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/sejm/term{term}/processes".replace("{" + "term" + "}", encodeURIComponent(term.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            body = localVariableBody,
        )
    }

    /**
     * GET /sejm/term{term}/processes/{num}/attachment/{fileName}
     * Returns an attachment for a process
     *
     * @param fileName an attachment name
     * @param num a print number
     * @param term a Sejm term
     * @return void
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Throws(
        IllegalStateException::class,
        IOException::class,
        UnsupportedOperationException::class,
        ClientException::class,
        ServerException::class,
    )
    fun sejmTermtermProcessesNumAttachmentFileNameGet(
        fileName: kotlin.String,
        num: kotlin.String,
        term: kotlin.Int,
    ) {
        val localVarResponse = sejmTermtermProcessesNumAttachmentFileNameGetWithHttpInfo(fileName = fileName, num = num, term = term)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> Unit
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException(
                    "Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}",
                    localVarError.statusCode,
                    localVarResponse,
                )
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException(
                    "Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}",
                    localVarError.statusCode,
                    localVarResponse,
                )
            }
        }
    }

    /**
     * GET /sejm/term{term}/processes/{num}/attachment/{fileName}
     * Returns an attachment for a process
     *
     * @param fileName an attachment name
     * @param num a print number
     * @param term a Sejm term
     * @return ApiResponse<Unit?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Throws(IllegalStateException::class, IOException::class)
    fun sejmTermtermProcessesNumAttachmentFileNameGetWithHttpInfo(
        fileName: kotlin.String,
        num: kotlin.String,
        term: kotlin.Int,
    ): ApiResponse<Unit?> {
        val localVariableConfig = sejmTermtermProcessesNumAttachmentFileNameGetRequestConfig(fileName = fileName, num = num, term = term)

        return request<Unit, Unit>(
            localVariableConfig,
        )
    }

    /**
     * To obtain the request config of the operation sejmTermtermProcessesNumAttachmentFileNameGet
     *
     * @param fileName an attachment name
     * @param num a print number
     * @param term a Sejm term
     * @return RequestConfig
     */
    fun sejmTermtermProcessesNumAttachmentFileNameGetRequestConfig(
        fileName: kotlin.String,
        num: kotlin.String,
        term: kotlin.Int,
    ): RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/sejm/term{term}/processes/{num}/attachment/{fileName}"
                .replace(
                    "{" + "fileName" + "}",
                    encodeURIComponent(fileName.toString()),
                ).replace(
                    "{" + "num" + "}",
                    encodeURIComponent(num.toString()),
                ).replace("{" + "term" + "}", encodeURIComponent(term.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            body = localVariableBody,
        )
    }

    /**
     * GET /sejm/term{term}/processes/{num}
     * Returns information about a process for a given print number
     *
     * @param num a print number
     * @param term a Sejm term
     * @return SejmProcessDetailsDto
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(
        IllegalStateException::class,
        IOException::class,
        UnsupportedOperationException::class,
        ClientException::class,
        ServerException::class,
    )
    fun sejmTermtermProcessesNumGet(
        num: kotlin.String,
        term: kotlin.Int,
    ): SejmProcessDetailsDto {
        val localVarResponse = sejmTermtermProcessesNumGetWithHttpInfo(num = num, term = term)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as SejmProcessDetailsDto
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException(
                    "Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}",
                    localVarError.statusCode,
                    localVarResponse,
                )
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException(
                    "Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}",
                    localVarError.statusCode,
                    localVarResponse,
                )
            }
        }
    }

    /**
     * GET /sejm/term{term}/processes/{num}
     * Returns information about a process for a given print number
     *
     * @param num a print number
     * @param term a Sejm term
     * @return ApiResponse<SejmProcessDetailsDto?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun sejmTermtermProcessesNumGetWithHttpInfo(
        num: kotlin.String,
        term: kotlin.Int,
    ): ApiResponse<SejmProcessDetailsDto?> {
        val localVariableConfig = sejmTermtermProcessesNumGetRequestConfig(num = num, term = term)

        return request<Unit, SejmProcessDetailsDto>(
            localVariableConfig,
        )
    }

    /**
     * To obtain the request config of the operation sejmTermtermProcessesNumGet
     *
     * @param num a print number
     * @param term a Sejm term
     * @return RequestConfig
     */
    fun sejmTermtermProcessesNumGetRequestConfig(
        num: kotlin.String,
        term: kotlin.Int,
    ): RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/sejm/term{term}/processes/{num}"
                .replace(
                    "{" + "num" + "}",
                    encodeURIComponent(num.toString()),
                ).replace("{" + "term" + "}", encodeURIComponent(term.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            body = localVariableBody,
        )
    }

    /**
     * GET /sejm/term{term}/processes/passed
     * Returns a list of passed legislative processes
     *
     * @param term a Sejm term
     * @param documentType a type of a document (optional)
     * @param limit controls the maximum number of items that may be returned for a single request (optional, default to 50)
     * @param modifiedSince filters processes  modified since specified date (optional)
     * @param offset controls the starting point within the collection of resource results (optional, default to 0)
     * @param passed only passed acts (optional)
     * @param sort sorts objects by specified field, to sort in descending order add a minus sign before field name (optional)
     * @param sortBy sorts objects by specified field, to sort in descending order add a minus sign before field name (optional)
     * @param title filters processes containing a specified string in a title (optional)
     * @return kotlin.collections.List<SejmProcessHeaderDto>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(
        IllegalStateException::class,
        IOException::class,
        UnsupportedOperationException::class,
        ClientException::class,
        ServerException::class,
    )
    fun sejmTermtermProcessesPassedGet(
        term: kotlin.Int,
        documentType: kotlin.String? = null,
        limit: kotlin.Int? = 50,
        modifiedSince: java.time.LocalDateTime? = null,
        offset: kotlin.Int? = 0,
        passed: kotlin.Boolean? = null,
        sort: kotlin.String? = null,
        sortBy: kotlin.String? = null,
        title: kotlin.String? = null,
    ): kotlin.collections.List<SejmProcessHeaderDto> {
        val localVarResponse =
            sejmTermtermProcessesPassedGetWithHttpInfo(
                term = term,
                documentType = documentType,
                limit = limit,
                modifiedSince = modifiedSince,
                offset = offset,
                passed = passed,
                sort = sort,
                sortBy = sortBy,
                title = title,
            )

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as kotlin.collections.List<SejmProcessHeaderDto>
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException(
                    "Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}",
                    localVarError.statusCode,
                    localVarResponse,
                )
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException(
                    "Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}",
                    localVarError.statusCode,
                    localVarResponse,
                )
            }
        }
    }

    /**
     * GET /sejm/term{term}/processes/passed
     * Returns a list of passed legislative processes
     *
     * @param term a Sejm term
     * @param documentType a type of a document (optional)
     * @param limit controls the maximum number of items that may be returned for a single request (optional, default to 50)
     * @param modifiedSince filters processes  modified since specified date (optional)
     * @param offset controls the starting point within the collection of resource results (optional, default to 0)
     * @param passed only passed acts (optional)
     * @param sort sorts objects by specified field, to sort in descending order add a minus sign before field name (optional)
     * @param sortBy sorts objects by specified field, to sort in descending order add a minus sign before field name (optional)
     * @param title filters processes containing a specified string in a title (optional)
     * @return ApiResponse<kotlin.collections.List<SejmProcessHeaderDto>?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun sejmTermtermProcessesPassedGetWithHttpInfo(
        term: kotlin.Int,
        documentType: kotlin.String?,
        limit: kotlin.Int?,
        modifiedSince: java.time.LocalDateTime?,
        offset: kotlin.Int?,
        passed: kotlin.Boolean?,
        sort: kotlin.String?,
        sortBy: kotlin.String?,
        title: kotlin.String?,
    ): ApiResponse<kotlin.collections.List<SejmProcessHeaderDto>?> {
        val localVariableConfig =
            sejmTermtermProcessesPassedGetRequestConfig(
                term = term,
                documentType = documentType,
                limit = limit,
                modifiedSince = modifiedSince,
                offset = offset,
                passed = passed,
                sort = sort,
                sortBy = sortBy,
                title = title,
            )

        return request<Unit, kotlin.collections.List<SejmProcessHeaderDto>>(
            localVariableConfig,
        )
    }

    /**
     * To obtain the request config of the operation sejmTermtermProcessesPassedGet
     *
     * @param term a Sejm term
     * @param documentType a type of a document (optional)
     * @param limit controls the maximum number of items that may be returned for a single request (optional, default to 50)
     * @param modifiedSince filters processes  modified since specified date (optional)
     * @param offset controls the starting point within the collection of resource results (optional, default to 0)
     * @param passed only passed acts (optional)
     * @param sort sorts objects by specified field, to sort in descending order add a minus sign before field name (optional)
     * @param sortBy sorts objects by specified field, to sort in descending order add a minus sign before field name (optional)
     * @param title filters processes containing a specified string in a title (optional)
     * @return RequestConfig
     */
    fun sejmTermtermProcessesPassedGetRequestConfig(
        term: kotlin.Int,
        documentType: kotlin.String?,
        limit: kotlin.Int?,
        modifiedSince: java.time.LocalDateTime?,
        offset: kotlin.Int?,
        passed: kotlin.Boolean?,
        sort: kotlin.String?,
        sortBy: kotlin.String?,
        title: kotlin.String?,
    ): RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
            .apply {
                if (documentType != null) {
                    put("documentType", listOf(documentType.toString()))
                }
                if (limit != null) {
                    put("limit", listOf(limit.toString()))
                }
                if (modifiedSince != null) {
                    put("modifiedSince", listOf(parseDateToQueryString<java.time.LocalDateTime>(modifiedSince)))
                }
                if (offset != null) {
                    put("offset", listOf(offset.toString()))
                }
                if (passed != null) {
                    put("passed", listOf(passed.toString()))
                }
                if (sort != null) {
                    put("sort", listOf(sort.toString()))
                }
                if (sortBy != null) {
                    put("sort_by", listOf(sortBy.toString()))
                }
                if (title != null) {
                    put("title", listOf(title.toString()))
                }
            }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/sejm/term{term}/processes/passed".replace("{" + "term" + "}", encodeURIComponent(term.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            body = localVariableBody,
        )
    }

    private fun encodeURIComponent(uriComponent: kotlin.String): kotlin.String =
        HttpUrl
            .Builder()
            .scheme("http")
            .host("localhost")
            .addPathSegment(uriComponent)
            .build()
            .encodedPathSegments[0]
}
