/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused",
)

package vote.fetcher.polishsejm.client.apis

import okhttp3.Call
import okhttp3.HttpUrl
import vote.fetcher.polishsejm.client.infrastructure.ApiClient
import vote.fetcher.polishsejm.client.infrastructure.ApiResponse
import vote.fetcher.polishsejm.client.infrastructure.ClientError
import vote.fetcher.polishsejm.client.infrastructure.ClientException
import vote.fetcher.polishsejm.client.infrastructure.MultiValueMap
import vote.fetcher.polishsejm.client.infrastructure.RequestConfig
import vote.fetcher.polishsejm.client.infrastructure.RequestMethod
import vote.fetcher.polishsejm.client.infrastructure.ResponseType
import vote.fetcher.polishsejm.client.infrastructure.ServerError
import vote.fetcher.polishsejm.client.infrastructure.ServerException
import vote.fetcher.polishsejm.client.infrastructure.Success
import vote.fetcher.polishsejm.client.models.SejmProceedingDto
import java.io.IOException

open class ProceedingsApi(basePath: kotlin.String = defaultBasePath, client: Call.Factory = ApiClient.defaultClient) : ApiClient(
    basePath,
    client,
) {
    companion object {
        @JvmStatic
        val defaultBasePath: String by lazy {
            System.getProperties().getProperty(ApiClient.BASE_URL_KEY, "https://api.sejm.gov.pl")
        }
    }

    /**
     * GET /sejm/term{term}/proceedings/current
     * Returns information about a current proceeding
     *
     * @param term a Sejm term
     * @return SejmProceedingDto
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(
        IllegalStateException::class,
        IOException::class,
        UnsupportedOperationException::class,
        ClientException::class,
        ServerException::class,
    )
    fun sejmTermtermProceedingsCurrentGet(term: kotlin.Int): SejmProceedingDto {
        val localVarResponse = sejmTermtermProceedingsCurrentGetWithHttpInfo(term = term)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as SejmProceedingDto
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException(
                    "Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}",
                    localVarError.statusCode,
                    localVarResponse,
                )
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException(
                    "Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}",
                    localVarError.statusCode,
                    localVarResponse,
                )
            }
        }
    }

    /**
     * GET /sejm/term{term}/proceedings/current
     * Returns information about a current proceeding
     *
     * @param term a Sejm term
     * @return ApiResponse<SejmProceedingDto?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun sejmTermtermProceedingsCurrentGetWithHttpInfo(term: kotlin.Int): ApiResponse<SejmProceedingDto?> {
        val localVariableConfig = sejmTermtermProceedingsCurrentGetRequestConfig(term = term)

        return request<Unit, SejmProceedingDto>(
            localVariableConfig,
        )
    }

    /**
     * To obtain the request config of the operation sejmTermtermProceedingsCurrentGet
     *
     * @param term a Sejm term
     * @return RequestConfig
     */
    fun sejmTermtermProceedingsCurrentGetRequestConfig(term: kotlin.Int): RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/sejm/term{term}/proceedings/current".replace("{" + "term" + "}", encodeURIComponent(term.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            body = localVariableBody,
        )
    }

    /**
     * GET /sejm/term{term}/proceedings
     * Returns a list of proceedings
     *
     * @param term a Sejm term
     * @return kotlin.collections.List<SejmProceedingDto>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(
        IllegalStateException::class,
        IOException::class,
        UnsupportedOperationException::class,
        ClientException::class,
        ServerException::class,
    )
    fun sejmTermtermProceedingsGet(term: kotlin.Int): kotlin.collections.List<SejmProceedingDto> {
        val localVarResponse = sejmTermtermProceedingsGetWithHttpInfo(term = term)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as kotlin.collections.List<SejmProceedingDto>
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException(
                    "Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}",
                    localVarError.statusCode,
                    localVarResponse,
                )
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException(
                    "Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}",
                    localVarError.statusCode,
                    localVarResponse,
                )
            }
        }
    }

    /**
     * GET /sejm/term{term}/proceedings
     * Returns a list of proceedings
     *
     * @param term a Sejm term
     * @return ApiResponse<kotlin.collections.List<SejmProceedingDto>?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun sejmTermtermProceedingsGetWithHttpInfo(term: kotlin.Int): ApiResponse<kotlin.collections.List<SejmProceedingDto>?> {
        val localVariableConfig = sejmTermtermProceedingsGetRequestConfig(term = term)

        return request<Unit, kotlin.collections.List<SejmProceedingDto>>(
            localVariableConfig,
        )
    }

    /**
     * To obtain the request config of the operation sejmTermtermProceedingsGet
     *
     * @param term a Sejm term
     * @return RequestConfig
     */
    fun sejmTermtermProceedingsGetRequestConfig(term: kotlin.Int): RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/sejm/term{term}/proceedings".replace("{" + "term" + "}", encodeURIComponent(term.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            body = localVariableBody,
        )
    }

    /**
     * GET /sejm/term{term}/proceedings/{id}
     * Returns information about a proceeding
     *
     * @param id a proceeding id
     * @param term a Sejm term
     * @return SejmProceedingDto
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(
        IllegalStateException::class,
        IOException::class,
        UnsupportedOperationException::class,
        ClientException::class,
        ServerException::class,
    )
    fun sejmTermtermProceedingsIdGet(
        id: kotlin.Int,
        term: kotlin.Int,
    ): SejmProceedingDto {
        val localVarResponse = sejmTermtermProceedingsIdGetWithHttpInfo(id = id, term = term)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as SejmProceedingDto
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException(
                    "Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}",
                    localVarError.statusCode,
                    localVarResponse,
                )
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException(
                    "Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}",
                    localVarError.statusCode,
                    localVarResponse,
                )
            }
        }
    }

    /**
     * GET /sejm/term{term}/proceedings/{id}
     * Returns information about a proceeding
     *
     * @param id a proceeding id
     * @param term a Sejm term
     * @return ApiResponse<SejmProceedingDto?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun sejmTermtermProceedingsIdGetWithHttpInfo(
        id: kotlin.Int,
        term: kotlin.Int,
    ): ApiResponse<SejmProceedingDto?> {
        val localVariableConfig = sejmTermtermProceedingsIdGetRequestConfig(id = id, term = term)

        return request<Unit, SejmProceedingDto>(
            localVariableConfig,
        )
    }

    /**
     * To obtain the request config of the operation sejmTermtermProceedingsIdGet
     *
     * @param id a proceeding id
     * @param term a Sejm term
     * @return RequestConfig
     */
    fun sejmTermtermProceedingsIdGetRequestConfig(
        id: kotlin.Int,
        term: kotlin.Int,
    ): RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/sejm/term{term}/proceedings/{id}"
                .replace(
                    "{" + "id" + "}",
                    encodeURIComponent(id.toString()),
                ).replace("{" + "term" + "}", encodeURIComponent(term.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            body = localVariableBody,
        )
    }

    private fun encodeURIComponent(uriComponent: kotlin.String): kotlin.String =
        HttpUrl
            .Builder()
            .scheme("http")
            .host("localhost")
            .addPathSegment(uriComponent)
            .build()
            .encodedPathSegments[0]
}
