/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused",
)

package vote.fetcher.polishsejm.client.apis

import okhttp3.Call
import okhttp3.HttpUrl
import vote.fetcher.polishsejm.client.infrastructure.ApiClient
import vote.fetcher.polishsejm.client.infrastructure.ApiResponse
import vote.fetcher.polishsejm.client.infrastructure.ClientError
import vote.fetcher.polishsejm.client.infrastructure.ClientException
import vote.fetcher.polishsejm.client.infrastructure.MultiValueMap
import vote.fetcher.polishsejm.client.infrastructure.RequestConfig
import vote.fetcher.polishsejm.client.infrastructure.RequestMethod
import vote.fetcher.polishsejm.client.infrastructure.ResponseType
import vote.fetcher.polishsejm.client.infrastructure.ServerError
import vote.fetcher.polishsejm.client.infrastructure.ServerException
import vote.fetcher.polishsejm.client.infrastructure.Success
import vote.fetcher.polishsejm.client.models.SejmStatementListDto
import java.io.IOException

open class TranscriptsApi(basePath: kotlin.String = defaultBasePath, client: Call.Factory = ApiClient.defaultClient) : ApiClient(
    basePath,
    client,
) {
    companion object {
        @JvmStatic
        val defaultBasePath: String by lazy {
            System.getProperties().getProperty(ApiClient.BASE_URL_KEY, "https://api.sejm.gov.pl")
        }
    }

    /**
     * GET /sejm/term{term}/proceedings/{id}/{date}/transcripts
     * Returns a list of statements
     *
     * @param date a sitting date
     * @param id a sitting id
     * @param term a Sejm term
     * @return SejmStatementListDto
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(
        IllegalStateException::class,
        IOException::class,
        UnsupportedOperationException::class,
        ClientException::class,
        ServerException::class,
    )
    fun sejmTermtermProceedingsIdDateTranscriptsGet(
        date: java.time.LocalDate,
        id: kotlin.Int,
        term: kotlin.Int,
    ): SejmStatementListDto {
        val localVarResponse = sejmTermtermProceedingsIdDateTranscriptsGetWithHttpInfo(date = date, id = id, term = term)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as SejmStatementListDto
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException(
                    "Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}",
                    localVarError.statusCode,
                    localVarResponse,
                )
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException(
                    "Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}",
                    localVarError.statusCode,
                    localVarResponse,
                )
            }
        }
    }

    /**
     * GET /sejm/term{term}/proceedings/{id}/{date}/transcripts
     * Returns a list of statements
     *
     * @param date a sitting date
     * @param id a sitting id
     * @param term a Sejm term
     * @return ApiResponse<SejmStatementListDto?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun sejmTermtermProceedingsIdDateTranscriptsGetWithHttpInfo(
        date: java.time.LocalDate,
        id: kotlin.Int,
        term: kotlin.Int,
    ): ApiResponse<SejmStatementListDto?> {
        val localVariableConfig = sejmTermtermProceedingsIdDateTranscriptsGetRequestConfig(date = date, id = id, term = term)

        return request<Unit, SejmStatementListDto>(
            localVariableConfig,
        )
    }

    /**
     * To obtain the request config of the operation sejmTermtermProceedingsIdDateTranscriptsGet
     *
     * @param date a sitting date
     * @param id a sitting id
     * @param term a Sejm term
     * @return RequestConfig
     */
    fun sejmTermtermProceedingsIdDateTranscriptsGetRequestConfig(
        date: java.time.LocalDate,
        id: kotlin.Int,
        term: kotlin.Int,
    ): RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/sejm/term{term}/proceedings/{id}/{date}/transcripts"
                .replace(
                    "{" + "date" + "}",
                    encodeURIComponent(date.toString()),
                ).replace(
                    "{" + "id" + "}",
                    encodeURIComponent(id.toString()),
                ).replace("{" + "term" + "}", encodeURIComponent(term.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            body = localVariableBody,
        )
    }

    /**
     * GET /sejm/term{term}/proceedings/{id}/{date}/transcripts/pdf
     * Returns a transcript of a day of a sitting in the PDF format
     *
     * @param date a sitting date
     * @param id a sitting id
     * @param term a Sejm term
     * @return void
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Throws(
        IllegalStateException::class,
        IOException::class,
        UnsupportedOperationException::class,
        ClientException::class,
        ServerException::class,
    )
    fun sejmTermtermProceedingsIdDateTranscriptsPdfGet(
        date: java.time.LocalDate,
        id: kotlin.Int,
        term: kotlin.Int,
    ) {
        val localVarResponse = sejmTermtermProceedingsIdDateTranscriptsPdfGetWithHttpInfo(date = date, id = id, term = term)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> Unit
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException(
                    "Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}",
                    localVarError.statusCode,
                    localVarResponse,
                )
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException(
                    "Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}",
                    localVarError.statusCode,
                    localVarResponse,
                )
            }
        }
    }

    /**
     * GET /sejm/term{term}/proceedings/{id}/{date}/transcripts/pdf
     * Returns a transcript of a day of a sitting in the PDF format
     *
     * @param date a sitting date
     * @param id a sitting id
     * @param term a Sejm term
     * @return ApiResponse<Unit?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Throws(IllegalStateException::class, IOException::class)
    fun sejmTermtermProceedingsIdDateTranscriptsPdfGetWithHttpInfo(
        date: java.time.LocalDate,
        id: kotlin.Int,
        term: kotlin.Int,
    ): ApiResponse<Unit?> {
        val localVariableConfig = sejmTermtermProceedingsIdDateTranscriptsPdfGetRequestConfig(date = date, id = id, term = term)

        return request<Unit, Unit>(
            localVariableConfig,
        )
    }

    /**
     * To obtain the request config of the operation sejmTermtermProceedingsIdDateTranscriptsPdfGet
     *
     * @param date a sitting date
     * @param id a sitting id
     * @param term a Sejm term
     * @return RequestConfig
     */
    fun sejmTermtermProceedingsIdDateTranscriptsPdfGetRequestConfig(
        date: java.time.LocalDate,
        id: kotlin.Int,
        term: kotlin.Int,
    ): RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/sejm/term{term}/proceedings/{id}/{date}/transcripts/pdf"
                .replace(
                    "{" + "date" + "}",
                    encodeURIComponent(date.toString()),
                ).replace(
                    "{" + "id" + "}",
                    encodeURIComponent(id.toString()),
                ).replace("{" + "term" + "}", encodeURIComponent(term.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            body = localVariableBody,
        )
    }

    /**
     * GET /sejm/term{term}/proceedings/{id}/{date}/transcripts/{statementNum}
     * Returns a statement body in the HTML format
     *
     * @param date a sitting date
     * @param id a sitting id
     * @param statementNum a statement number
     * @param term a Sejm term
     * @return void
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Throws(
        IllegalStateException::class,
        IOException::class,
        UnsupportedOperationException::class,
        ClientException::class,
        ServerException::class,
    )
    fun sejmTermtermProceedingsIdDateTranscriptsStatementNumGet(
        date: java.time.LocalDate,
        id: kotlin.Int,
        statementNum: kotlin.Int,
        term: kotlin.Int,
    ) {
        val localVarResponse =
            sejmTermtermProceedingsIdDateTranscriptsStatementNumGetWithHttpInfo(
                date = date,
                id = id,
                statementNum = statementNum,
                term = term,
            )

        return when (localVarResponse.responseType) {
            ResponseType.Success -> Unit
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException(
                    "Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}",
                    localVarError.statusCode,
                    localVarResponse,
                )
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException(
                    "Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}",
                    localVarError.statusCode,
                    localVarResponse,
                )
            }
        }
    }

    /**
     * GET /sejm/term{term}/proceedings/{id}/{date}/transcripts/{statementNum}
     * Returns a statement body in the HTML format
     *
     * @param date a sitting date
     * @param id a sitting id
     * @param statementNum a statement number
     * @param term a Sejm term
     * @return ApiResponse<Unit?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Throws(IllegalStateException::class, IOException::class)
    fun sejmTermtermProceedingsIdDateTranscriptsStatementNumGetWithHttpInfo(
        date: java.time.LocalDate,
        id: kotlin.Int,
        statementNum: kotlin.Int,
        term: kotlin.Int,
    ): ApiResponse<Unit?> {
        val localVariableConfig =
            sejmTermtermProceedingsIdDateTranscriptsStatementNumGetRequestConfig(
                date = date,
                id = id,
                statementNum = statementNum,
                term = term,
            )

        return request<Unit, Unit>(
            localVariableConfig,
        )
    }

    /**
     * To obtain the request config of the operation sejmTermtermProceedingsIdDateTranscriptsStatementNumGet
     *
     * @param date a sitting date
     * @param id a sitting id
     * @param statementNum a statement number
     * @param term a Sejm term
     * @return RequestConfig
     */
    fun sejmTermtermProceedingsIdDateTranscriptsStatementNumGetRequestConfig(
        date: java.time.LocalDate,
        id: kotlin.Int,
        statementNum: kotlin.Int,
        term: kotlin.Int,
    ): RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/sejm/term{term}/proceedings/{id}/{date}/transcripts/{statementNum}"
                .replace(
                    "{" + "date" + "}",
                    encodeURIComponent(date.toString()),
                ).replace(
                    "{" + "id" + "}",
                    encodeURIComponent(id.toString()),
                ).replace("{" + "statementNum" + "}", encodeURIComponent(statementNum.toString()))
                .replace(
                    "{" + "term" + "}",
                    encodeURIComponent(term.toString()),
                ),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            body = localVariableBody,
        )
    }

    private fun encodeURIComponent(uriComponent: kotlin.String): kotlin.String =
        HttpUrl
            .Builder()
            .scheme("http")
            .host("localhost")
            .addPathSegment(uriComponent)
            .build()
            .encodedPathSegments[0]
}
